default:
  target: duckdb
  outputs:
    duckdb:
      type: duckdb
      path: target/dbt-hubspot.duckdb
      extensions:
        - httpfs
        - parquet
    motherduck:
      type: duckdb
      path: "md:airbyte_hubspot"
      extensions:
        - httpfs
        - parquet
      settings:
        motherduck_token: ${MOTHERDUCK_TOKEN}
