default:
  target: duckdb
  outputs:
    duckdb:
      type: duckdb
      # Assume we are running from `morph/catalog/{source-name}/dbt_project/`
      # and that repo root is 4 levels up.
      path: ../../../../.data/hubspot.duckdb
      extensions:
        - httpfs
        - parquet
    motherduck:
      type: duckdb
      path: "md:airbyte_hubspot"
      extensions:
        - httpfs
        - parquet
      settings:
        motherduck_token: ${MOTHERDUCK_TOKEN}
