
-- This file was autogenerated with Airbyte Morph. Please do not modify directly.

WITH
account_notes AS (
    SELECT * FROM {{ source('recurly', 'account_notes') }}
)


SELECT
    account_notes.id AS id,
    account_notes.account_id AS account_id,
    NULL AS account_updated_at,
    account_notes.created_at AS created_at,
    account_notes.message AS message,
    account_notes.object AS object,
    account_notes.user.id AS user_id,
    account_notes.user.email AS user_email
FROM account_notes
