
-- This file was autogenerated with Airbyte Morph. Please do not modify directly.

WITH
account_coupon_redemptions AS (
    SELECT * FROM {{ source('recurly', 'account_coupon_redemptions') }}
)


SELECT
    account_coupon_redemptions.id AS id,
    account_coupon_redemptions.account.id AS account_id,
    account_coupon_redemptions.coupon.id AS coupon_id,
    account_coupon_redemptions.created_at AS created_at,
    account_coupon_redemptions.currency AS currency,
    account_coupon_redemptions.discounted AS discounted,
    account_coupon_redemptions.removed_at AS removed_at,
    account_coupon_redemptions.state AS state,
    account_coupon_redemptions.updated_at AS updated_at
FROM account_coupon_redemptions
