
-- This file was autogenerated with Airbyte Morph. Please do not modify directly.

WITH
coupons AS (
    SELECT * FROM {{ source('recurly', 'coupons') }}
)


SELECT
    coupons.id AS coupon_id,
    coupons.id AS fivetran_id,
    coupons.discount AS amount,
    coupons.discount.currencies AS currency,
    coupons.discount.percent AS percentage,
    coupons.discount.trial.length AS trial_length,
    coupons.discount.trial.unit AS trial_unit,
    coupons.discount.type AS type
FROM coupons
