
-- This file was autogenerated with Airbyte Morph. Please do not modify directly.

WITH
campaigns AS (
    SELECT * FROM {{ source('tiktok_marketing', 'campaigns') }}
)


SELECT
    campaigns.campaign_id AS campaign_id,
    campaigns.modify_time AS updated_at,
    campaigns.advertiser_id AS advertiser_id,
    campaigns.budget AS budget,
    campaigns.budget_mode AS budget_mode,
    campaigns.campaign_name AS campaign_name,
    campaigns.campaign_type AS campaign_type,
    campaigns.create_time AS create_time,
    campaigns.is_new_structure AS is_new_structure,
    campaigns.objective_type AS objective_type,
    campaigns.operation_status AS opt_status,
    campaigns.secondary_status AS status,
    campaigns.split_test_variable AS split_test_variable
FROM campaigns
