project_id: stripe.airbyte-interop
source_name: stripe
# Target schema file snapshotted from: https://github.com/fivetran/dbt_stripe_source/blob/main/models/src_stripe.yml
target_dbt_schema_url: https://raw.githubusercontent.com/fivetran/dbt_stripe_source/refs/heads/main/models/src_stripe.yml
# SQL dialect configuration
sql_dialect: duckdb
subcolumn_traversal: dot_notation
