
-- This file was autogenerated with Morph. Please do not modify directly.

WITH
activities_email_delivered AS (
    SELECT * FROM {{ source('marketo', 'activities_email_delivered') }}
)


SELECT
    activities_email_delivered.activityDate AS activity_date,
    activities_email_delivered.activityTypeId AS activity_type_id,
    activities_email_delivered.campaignId AS campaign_id,
    activities_email_delivered.campaign_run_id AS campaign_run_id,
    activities_email_delivered.choice_number AS choice_number,
    NULL AS email_template_id,
    NULL AS id,
    activities_email_delivered.leadId AS lead_id,
    activities_email_delivered.primaryAttributeValue AS primary_attribute_value,
    activities_email_delivered.primaryAttributeValueId AS primary_attribute_value_id,
    activities_email_delivered.step_id AS step_id
FROM activities_email_delivered
