
-- This file was autogenerated with Morph. Please do not modify directly.

WITH
activities_delete_lead AS (
    SELECT * FROM {{ source('marketo', 'activities_delete_lead') }}
)


SELECT
    activities_delete_lead.activityDate AS activity_date,
    activities_delete_lead.activityTypeId AS activity_type_id,
    activities_delete_lead.campaignId AS campaign_id,
    NULL AS campaign,
    activities_delete_lead.marketoGUID AS id,
    activities_delete_lead.leadId AS lead_id,
    NULL AS primary_attribute_value,
    activities_delete_lead.primaryAttributeValueId AS primary_attribute_value_id
FROM activities_delete_lead
