
-- This file was autogenerated with Morph. Please do not modify directly.

WITH
activities_merge_leads AS (
    SELECT * FROM {{ source('marketo', 'activities_merge_leads') }}
)


SELECT
    activities_merge_leads.activityDate AS activity_date,
    activities_merge_leads.activityTypeId AS activity_type_id,
    activities_merge_leads.campaignId AS campaign_id,
    activities_merge_leads.marketoGUID AS id,
    activities_merge_leads.leadId AS lead_id,
    activities_merge_leads.primaryAttributeValue AS primary_attribute_value,
    activities_merge_leads.primaryAttributeValueId AS primary_attribute_value_id,
    activities_merge_leads.merge_ids AS merge_ids
FROM activities_merge_leads
