
-- This file was autogenerated with Morph. Please do not modify directly.

WITH
activities_email_bounced AS (
    SELECT * FROM {{ source('marketo', 'activities_email_bounced') }}
)


SELECT
    activities_email_bounced.activityDate AS activity_date,
    activities_email_bounced.activityTypeId AS activity_type_id,
    activities_email_bounced.campaignId AS campaign_id,
    activities_email_bounced.campaign_run_id AS campaign_run_id,
    activities_email_bounced.category AS category,
    activities_email_bounced.choice_number AS choice_number,
    activities_email_bounced.details AS details,
    activities_email_bounced.email AS email,
    activities_email_bounced.email AS email_template_id,
    activities_email_bounced.marketoGUID AS id,
    activities_email_bounced.leadId AS lead_id,
    activities_email_bounced.primaryAttributeValue AS primary_attribute_value,
    activities_email_bounced.primaryAttributeValueId AS primary_attribute_value_id,
    activities_email_bounced.step_id AS step_id,
    activities_email_bounced.subcategory AS subcategory
FROM activities_email_bounced
