
-- This file was autogenerated with Morph. Please do not modify directly.

WITH
activities_unsubscribe_email AS (
    SELECT * FROM {{ source('marketo', 'activities_unsubscribe_email') }}
)


SELECT
    activities_unsubscribe_email.activityDate AS activity_date,
    activities_unsubscribe_email.activityTypeId AS activity_type_id,
    activities_unsubscribe_email.campaignId AS campaign_id,
    activities_unsubscribe_email.campaign_run_id AS campaign_run_id,
    activities_unsubscribe_email.client_ip_address AS client_ip_address,
    NULL AS email_template_id,
    activities_unsubscribe_email.form_fields AS form_fields,
    activities_unsubscribe_email.marketoGUID AS id,
    activities_unsubscribe_email.leadId AS lead_id,
    activities_unsubscribe_email.primaryAttributeValue AS primary_attribute_value,
    activities_unsubscribe_email.primaryAttributeValueId AS primary_attribute_value_id,
    activities_unsubscribe_email.query_parameters AS query_parameters,
    activities_unsubscribe_email.referrer_url AS referrer_url,
    activities_unsubscribe_email.user_agent AS user_agent,
    activities_unsubscribe_email.webform_id AS webform_id,
    activities_unsubscribe_email.webpage_id AS webpage_id
FROM activities_unsubscribe_email
