
-- This file was autogenerated with Morph. Please do not modify directly.

WITH
activities_open_email AS (
    SELECT * FROM {{ source('marketo', 'activities_open_email') }}
)


SELECT
    activities_open_email.activityDate AS activity_date,
    activities_open_email.activityTypeId AS activity_type_id,
    activities_open_email.campaignId AS campaign_id,
    activities_open_email.campaign_run_id AS campaign_run_id,
    activities_open_email.choice_number AS choice_number,
    activities_open_email.device AS device,
    NULL AS email_template_id,
    activities_open_email.marketoGUID AS id,
    activities_open_email.is_mobile_device AS is_mobile_device,
    activities_open_email.leadId AS lead_id,
    activities_open_email.platform AS platform,
    activities_open_email.primaryAttributeValue AS primary_attribute_value,
    activities_open_email.primaryAttributeValueId AS primary_attribute_value_id,
    activities_open_email.step_id AS step_id,
    activities_open_email.user_agent AS user_agent
FROM activities_open_email
