
-- This file was autogenerated with Morph. Please do not modify directly.

WITH
activities_send_email AS (
    SELECT * FROM {{ source('marketo', 'activities_send_email') }}
)


SELECT
    NULL AS action_result,
    activities_send_email.activityDate AS activity_date,
    activities_send_email.activityTypeId AS activity_type_id,
    activities_send_email.campaignId AS campaign_id,
    activities_send_email.campaign_run_id AS campaign_run_id,
    activities_send_email.choice_number AS choice_number,
    NULL AS email_template_id,
    activities_send_email.marketoGUID AS id,
    activities_send_email.leadId AS lead_id,
    activities_send_email.primaryAttributeValue AS primary_attribute_value,
    activities_send_email.primaryAttributeValueId AS primary_attribute_value_id,
    activities_send_email.step_id AS step_id
FROM activities_send_email
