
-- This file was autogenerated with Morph. Please do not modify directly.

WITH
activities_click_email AS (
    SELECT * FROM {{ source('marketo', 'activities_click_email') }}
)


SELECT
    activities_click_email.activityDate AS activity_date,
    activities_click_email.activityTypeId AS activity_type_id,
    activities_click_email.campaignId AS campaign_id,
    activities_click_email.campaign_run_id AS campaign_run_id,
    activities_click_email.choice_number AS choice_number,
    activities_click_email.device AS device,
    NULL AS email_template_id,
    NULL AS id,
    activities_click_email.is_mobile_device AS is_mobile_device,
    activities_click_email.leadId AS lead_id,
    activities_click_email.link AS link,
    activities_click_email.primaryAttributeValue AS primary_attribute_value,
    activities_click_email.primaryAttributeValueId AS primary_attribute_value_id,
    activities_click_email.step_id AS step_id,
    activities_click_email.user_agent AS user_agent
FROM activities_click_email
