
-- This file was autogenerated with Morph. Please do not modify directly.

WITH
activities_change_data_value AS (
    SELECT * FROM {{ source('marketo', 'activities_change_data_value') }}
)


SELECT
    activities_change_data_value.api_method_name AS api_method_name,
    activities_change_data_value.activityDate AS activity_date,
    activities_change_data_value.activityTypeId AS activity_type_id,
    activities_change_data_value.campaignId AS campaign_id,
    activities_change_data_value.marketoGUID AS id,
    activities_change_data_value.leadId AS lead_id,
    activities_change_data_value.modifying_user AS modifying_user,
    activities_change_data_value.new_value AS new_value,
    activities_change_data_value.old_value AS old_value,
    activities_change_data_value.primaryAttributeValue AS primary_attribute_value,
    activities_change_data_value.primaryAttributeValueId AS primary_attribute_value_id,
    activities_change_data_value.reason AS reason,
    activities_change_data_value.request_id AS request_id
FROM activities_change_data_value
