
-- This file was autogenerated with Morph. Please do not modify directly.

WITH
ads_insights AS (
    SELECT * FROM {{ source('facebook_marketing', 'ads_insights') }}
)


SELECT
    ads_insights.ad_id AS ad_id,
    ads_insights.ad_name AS ad_name,
    ads_insights.adset_name AS adset_name,
    ads_insights.date_stop AS date,
    ads_insights.account_id AS account_id,
    ads_insights.impressions AS impressions,
    ads_insights.inline_link_clicks AS inline_link_clicks,
    ads_insights.spend AS spend,
    ads_insights.reach AS reach,
    ads_insights.frequency AS frequency,
    ads_insights._airbyte_extracted_at AS _fivetran_synced
FROM ads_insights
