
-- This file was autogenerated with Morph. Please do not modify directly.

WITH
flows AS (
    SELECT * FROM {{ source('klaviyo', 'flows') }}
)


SELECT
    flows.attributes.created AS created,
    flows.id AS id,
    flows.attributes.name AS name,
    flows.attributes.status AS status,
    flows.attributes.updated AS updated,
    flows.attributes.archived AS archived,
    flows.attributes.trigger_type AS trigger_type,
    NULL AS _fivetran_deleted
FROM flows
