extends: default

ignore: |
  **/generated/**
  **/requirements/**

rules:
  line-length:
    max: 100
    level: warning
  document-start: disable
  truthy:
    allowed-values: ["true", "false", "on", "off", "yes", "no"]
