[tool.poe.tasks]
# Development tasks
install = { cmd = "uv sync --all-extras --all-groups", "Install and sync project dependencies." }
format = { cmd = "ruff format .", help = "Format code with ruff" }
lint = { cmd = "ruff check .", help = "Lint code with ruff" }
typecheck = { cmd = "python -m basedpyright morph", help = "Type check code with basedpyright" }
test = { cmd = "pytest", help = "Run tests with pytest" }
test-cov = { cmd = "pytest --cov=morph --cov-report=term-missing --cov-report=xml", help = "Run tests with coverage" }

# Combined tasks
check = { sequence = ["lint", "typecheck", "test"], help = "Run all checks" }
fix = { sequence = ["format", "lint --fix"], help = "Auto-fix formatting and linting issues" }

# Build tasks
build = { cmd = "python -m build", help = "Build package" }
clean = { cmd = "rm -rf build dist *.egg-info", help = "Clean build artifacts" }

# Dependency management
lock = { cmd = "uv pip compile requirements.txt requirements-dev.txt --output-file=requirements.lock", help = "Lock dependencies" }
