[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "morph"
version = "0.1.0"
description = "A Python library for data transformation"
readme = "README.md"
requires-python = ">=3.10"
license = {file = "LICENSE"}
authors = [
    {name = "Aaron Steers", email = "aaron.steers@airbyte.io"},
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: Other/Proprietary License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Typing :: Typed",
]
dependencies = [
    "click>=8.0.0",
    "rich>=10.0.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "pytest-cov>=4.0.0",
    "ruff>=0.0.292",
    "basedpyright>=1.0.0",
    "poethepoet>=0.24.0",
    "pre-commit>=3.0.0",
]

[project.urls]
Homepage = "https://github.com/airbytehq/morph"
Issues = "https://github.com/airbytehq/morph/issues"

[project.scripts]
morph = "morph.cli:main"
