[project]
source_name = "shopify"
project_name = "fivetran-interop"
generated_at = "2025-03-31T15:44:13Z"
requirements_file = "catalog/shopify/requirements/fivetran-interop/src_dbt_requirements.yml"
requirements_file_hash = "f022b53cac87e62f4af57a4a9e491e879843c5e70fd63b0ba0451f94c85fb0b3"
airbyte_source_file = "catalog/shopify/generated/src_airbyte_shopify.yml"
airbyte_source_file_hash = "4bf1aea92cc927f957a8271e56602fb1bdc93c2e827b581177f3b42a5d21caa4"

[coverage]
unused_source_streams = [
    "abandoned_checkouts",
    "articles",
    "balance_transactions",
    "blogs",
    "collections",
    "collects",
    "countries",
    "custom_collections",
    "customer_address",
    "customer_journey_summary",
    "customers",
    "discount_codes",
    "disputes",
    "draft_orders",
    "fulfillment_orders",
    "fulfillments",
    "inventory_items",
    "inventory_levels",
    "locations",
    "metafield_articles",
    "metafield_blogs",
    "metafield_collections",
    "metafield_customers",
    "metafield_draft_orders",
    "metafield_locations",
    "metafield_orders",
    "metafield_pages",
    "metafield_product_images",
    "metafield_product_variants",
    "metafield_products",
    "metafield_shops",
    "metafield_smart_collections",
    "order_agreements",
    "order_refunds",
    "order_risks",
    "orders",
    "pages",
    "price_rules",
    "product_images",
    "product_variants",
    "products",
    "shop",
    "smart_collections",
    "tender_transactions",
    "transactions",
]
unmapped_target_tables = [
    "abandoned_checkout",
    "abandoned_checkout_discount_code",
    "abandoned_checkout_shipping_line",
    "collection",
    "collection_product",
    "customer",
    "customer_tag",
    "discount_code",
    "fulfillment",
    "fulfillment_event",
    "inventory_item",
    "inventory_level",
    "inventory_quantity",
    "location",
    "metafield",
    "order",
    "order_adjustment",
    "order_discount_code",
    "order_line",
    "order_line_refund",
    "order_note_attribute",
    "order_shipping_line",
    "order_shipping_tax_line",
    "order_tag",
    "order_url_tag",
    "price_rule",
    "product",
    "product_image",
    "product_tag",
    "product_variant",
    "refund",
    "shop",
    "tax_line",
    "tender_transaction",
    "transaction",
]

[mappings]
