domain: shopify.fivetran-interop
transforms:
  - name: product_variant
    from:
      - product_variants: shopify.product_variants
    fields:
      barcode:
        expression: product_variants.barcode
        description: The barcode, UPC, or ISBN number for the product.
      compare_at_price:
        expression: product_variants.compare_at_price
        description: The original price of the item before an adjustment or a sale
          in shop currency.
      created_at:
        expression: product_variants.created_at
        description: The date and time (ISO 8601 format) when the product variant
          was created.
      fulfillment_service:
        expression: MISSING
        description: (DEPRECATED 2025-01-06) The fulfillment service associated with
          the product variant.
      grams:
        expression: product_variants.grams
        description: (DEPRECATED 2025-01-06) The weight of the product variant in
          grams.
      id:
        expression: product_variants.id
        description: The unique numeric identifier for the product variant.
      image_id:
        expression: product_variants.image_id
        description: The unique numeric identifier for a product's image. The image
          must be associated to the same product as the variant.
      inventory_item_id:
        expression: product_variants.inventory_item_id
        description: The unique identifier for the inventory item, which is used in
          the Inventory API to query for inventory information.
      inventory_management:
        expression: MISSING
        description: (DEPRECATED 2025-01-06) The fulfillment service that tracks the
          number of items in stock for the product variant.
      inventory_policy:
        expression: product_variants.inventory_policy
        description: Whether customers are allowed to place an order for the product
          variant when it's out of stock.
      inventory_quantity:
        expression: product_variants.inventory_quantity
        description: An aggregate of inventory across all locations. To adjust inventory
          at a specific location, use the InventoryLevel resource.
      old_inventory_quantity:
        expression: product_variants.old_inventory_quantity
        description: (DEPRECATED 2025-01-06) Use the InventoryLevel resource instead.
      option_1:
        expression: product_variants.option1
        description: "(DEPRECATED 2025-01-06) The custom properties that a shop owner
          uses to define product variants. You can define three options for a product
          variant: option1, option2, option3.\n"
      option_2:
        expression: product_variants.option2
        description: "(DEPRECATED 2025-01-06) The custom properties that a shop owner
          uses to define product variants. You can define three options for a product
          variant: option1, option2, option3.\n"
      option_3:
        expression: product_variants.option3
        description: "(DEPRECATED 2025-01-06) The custom properties that a shop owner
          uses to define product variants. You can define three options for a product
          variant: option1, option2, option3.\n"
      position:
        expression: product_variants.position
        description: The order of the product variant in the list of product variants.
          The first position in the list is 1. The position of variants is indicated
          by the order in which they are listed.
      price:
        expression: product_variants.price
        description: The price of the product variant in shop currency.
      product_id:
        expression: product_variants.product_id
        description: The unique numeric identifier for the product.
      requires_shipping:
        expression: product_variants.requires_shipping
        description: (DEPRECATED 2025-01-06) Use the `requires_shipping` property
          on the InventoryItem resource instead.
      sku:
        expression: product_variants.sku
        description: A unique identifier for the product variant in the shop. Required
          in order to connect to a FulfillmentService.
      taxable:
        expression: product_variants.taxable
        description: Whether a tax is charged when the product variant is sold.
      tax_code:
        expression: product_variants.tax_code
        description: This parameter applies only to the stores that have the Avalara
          AvaTax app installed. Specifies the Avalara tax code for the product variant.
      title:
        expression: product_variants.title
        description: The title of the product variant. The title field is a concatenation
          of the option1, option2, and option3 fields. You can only update title indirectly
          using the option fields.
      updated_at:
        expression: product_variants.updated_at
        description: The date and time when the product variant was last modified.
          Gets returned in ISO 8601 format.
      weight:
        expression: product_variants.weight
        description: (DEPRECATED 2025-01-06) The weight of the product variant in
          the unit system specified with weight_unit.
      weight_unit:
        expression: product_variants.weight_unit
        description: "(DEPRECATED 2025-01-06) The unit of measurement that applies
          to the product variant's weight. If you don't specify a value for weight_unit,
          then the shop's default unit of measurement is applied. Valid values: g,
          kg, oz, and lb.\n"
      available_for_sale:
        expression: product_variants.available_for_sale
        description: Indicates whether the product variant is available for sale.
      display_name:
        expression: product_variants.display_name
        description: The display name of the variant, based on the product's title
          and variant's title.
      legacy_resource_id:
        expression: MISSING
        description: The ID of the corresponding resource in the REST Admin API.
      metafield:
        expression: MISSING
        description: A custom field, including its namespace and key, that's associated
          with a Shopify resource for the purposes of adding and storing additional
          information.
      requires_components:
        expression: MISSING
        description: Indicates whether a product variant requires components.
      sellable_online_quantity:
        expression: MISSING
        description: The total sellable quantity of the variant for online channels.
      _fivetran_synced:
        expression: product_variants._airbyte_extracted_at
        description: "{{ doc('_fivetran_synced') }}"
annotations:
  approved: false
  missing_fields:
    - fulfillment_service
    - inventory_management
    - legacy_resource_id
    - metafield
    - requires_components
    - sellable_online_quantity
  evaluation:
    source_stream_name: product_variants
    target_table_name: product_variant
    table_match_score: 0.8
    completion_score: 0.6
    explanation: The table mapping is mostly consistent with the target schema, but
      there are several fields marked as 'MISSING' due to lack of good matches or
      differences in field representation. The overall table match score is high due
      to shared subject matter and relevant fields, but the completion score is lower
      reflecting these gaps.
    field_mapping_evals:
      - name: barcode
        expression: product_variants.barcode
        score: 0.9
        explanation: The mapping of 'barcode' is strong as it directly corresponds
          to 'product_variants.barcode'.
      - name: compare_at_price
        expression: product_variants.compare_at_price
        score: 0.9
        explanation: The mapping of 'compare_at_price' is strong as it directly corresponds
          to 'product_variants.compare_at_price'.
      - name: created_at
        expression: product_variants.created_at
        score: 0.9
        explanation: The mapping of 'created_at' is strong as it directly corresponds
          to 'product_variants.created_at'.
      - name: fulfillment_service
        expression: MISSING
        score: 0.0
        explanation: No good match found.
      - name: grams
        expression: product_variants.grams
        score: 0.9
        explanation: The mapping of 'grams' is strong as it directly corresponds to
          'product_variants.grams'.
      - name: id
        expression: product_variants.id
        score: 0.9
        explanation: The mapping of 'id' is strong as it directly corresponds to 'product_variants.id'.
      - name: image_id
        expression: product_variants.image_id
        score: 0.9
        explanation: The mapping of 'image_id' is strong as it directly corresponds
          to 'product_variants.image_id'.
      - name: inventory_item_id
        expression: product_variants.inventory_item_id
        score: 0.9
        explanation: The mapping of 'inventory_item_id' is strong as it directly corresponds
          to 'product_variants.inventory_item_id'.
      - name: inventory_management
        expression: MISSING
        score: 0.0
        explanation: No good match found.
      - name: inventory_policy
        expression: product_variants.inventory_policy
        score: 0.9
        explanation: The mapping of 'inventory_policy' is strong as it directly corresponds
          to 'product_variants.inventory_policy'.
      - name: inventory_quantity
        expression: product_variants.inventory_quantity
        score: 0.9
        explanation: The mapping of 'inventory_quantity' is strong as it directly
          corresponds to 'product_variants.inventory_quantity'.
      - name: old_inventory_quantity
        expression: product_variants.old_inventory_quantity
        score: 0.9
        explanation: The mapping of 'old_inventory_quantity' is strong as it directly
          corresponds to 'product_variants.old_inventory_quantity'.
      - name: option_1
        expression: product_variants.option1
        score: 0.9
        explanation: The mapping of 'option_1' is strong as it directly corresponds
          to 'product_variants.option1'.
      - name: option_2
        expression: product_variants.option2
        score: 0.9
        explanation: The mapping of 'option_2' is strong as it directly corresponds
          to 'product_variants.option2'.
      - name: option_3
        expression: product_variants.option3
        score: 0.9
        explanation: The mapping of 'option_3' is strong as it directly corresponds
          to 'product_variants.option3'.
      - name: position
        expression: product_variants.position
        score: 0.9
        explanation: The mapping of 'position' is strong as it directly corresponds
          to 'product_variants.position'.
      - name: price
        expression: product_variants.price
        score: 0.9
        explanation: The mapping of 'price' is strong as it directly corresponds to
          'product_variants.price'.
      - name: product_id
        expression: product_variants.product_id
        score: 0.9
        explanation: The mapping of 'product_id' is strong as it directly corresponds
          to 'product_variants.product_id'.
      - name: requires_shipping
        expression: product_variants.requires_shipping
        score: 0.0
        explanation: No good match found.
      - name: sku
        expression: product_variants.sku
        score: 0.9
        explanation: The mapping of 'sku' is strong as it directly corresponds to
          'product_variants.sku'.
      - name: taxable
        expression: product_variants.taxable
        score: 0.9
        explanation: The mapping of 'taxable' is strong as it directly corresponds
          to 'product_variants.taxable'.
      - name: tax_code
        expression: product_variants.tax_code
        score: 0.9
        explanation: The mapping of 'tax_code' is strong as it directly corresponds
          to 'product_variants.tax_code'.
      - name: title
        expression: product_variants.title
        score: 0.9
        explanation: The mapping of 'title' is strong as it directly corresponds to
          'product_variants.title'.
      - name: updated_at
        expression: product_variants.updated_at
        score: 0.9
        explanation: The mapping of 'updated_at' is strong as it directly corresponds
          to 'product_variants.updated_at'.
      - name: weight
        expression: product_variants.weight
        score: 0.9
        explanation: The mapping of 'weight' is strong as it directly corresponds
          to 'product_variants.weight'.
      - name: weight_unit
        expression: product_variants.weight_unit
        score: 0.9
        explanation: The mapping of 'weight_unit' is strong as it directly corresponds
          to 'product_variants.weight_unit'.
      - name: available_for_sale
        expression: product_variants.available_for_sale
        score: 0.9
        explanation: The mapping of 'available_for_sale' is strong as it directly
          corresponds to 'product_variants.available_for_sale'.
      - name: display_name
        expression: product_variants.display_name
        score: 0.9
        explanation: The mapping of 'display_name' is strong as it directly corresponds
          to 'product_variants.display_name'.
      - name: legacy_resource_id
        expression: MISSING
        score: 0.0
        explanation: No good match found.
      - name: metafield
        expression: MISSING
        score: 0.0
        explanation: No good match found.
      - name: requires_components
        expression: MISSING
        score: 0.0
        explanation: No good match found.
      - name: sellable_online_quantity
        expression: MISSING
        score: 0.0
        explanation: No good match found.
      - name: _fivetran_synced
        expression: product_variants._airbyte_extracted_at
        score: 1.0
        explanation: The mapping of '_fivetran_synced' to '_airbyte_extracted_at'
          is perfect and standard for all tables.
