domain: shopify.fivetran-interop
transforms:
  - name: product_tag
    from:
      - products: shopify.products
    fields:
      _fivetran_synced:
        expression: products._airbyte_extracted_at
        description: "{{ doc('_fivetran_synced') }}"
      index:
        expression: MISSING
        description:
          Index (starting from 1) represnting when the tag was placed on
          the product.
      product_id:
        expression: MISSING
        description: ID of the product being tagged.
      value:
        expression: MISSING
        description: Value of the tag.
annotations:
  approved: false
  missing_fields:
    - index
    - product_id
    - value
  evaluation:
    source_stream_name: products
    target_table_name: product_tag
    table_match_score: 1.0
    completion_score: 0.25
    explanation:
      The mapping configuration exhibits a perfect table match with successful
      standard field mapping for '_fivetran_synced', but lacks completion with most
      fields having 'MISSING' expressions.
    field_mapping_evals:
      - name: _fivetran_synced
        expression: products._airbyte_extracted_at
        score: 1.0
        explanation: Standard mapping of '_fivetran_synced' to '_airbyte_extracted_at'.
      - name: index
        expression: MISSING
        score: 0.0
        explanation: No good match found.
      - name: product_id
        expression: MISSING
        score: 0.0
        explanation: No good match found.
      - name: value
        expression: MISSING
        score: 0.0
        explanation: No good match found.
