domain: shopify.fivetran-interop
transforms:
  - name: product_tag
    from:
      - product_variants: shopify.product_variants
    fields:
      _fivetran_synced:
        expression: product_variants._airbyte_extracted_at
        description: "{{ doc('_fivetran_synced') }}"
      index:
        expression: product_variants.position
        description: Index (starting from 1) represnting when the tag was placed on
          the product.
      product_id:
        expression: product_variants.product_id
        description: ID of the product being tagged.
      value:
        expression: MISSING
        description: Value of the tag.
