name: "airbyte_{{ catalog_name }}"
version: "1.0.0"
config-version: 2

profile: "default"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  airbyte_{{ catalog_name }}:
    +materialized: view

    # Workshop models (not yet approved)
    workshop:
      +enabled: false  # Workshop models are disabled by default

vars:
  airbyte_{{ catalog_name }}_database: "{{ catalog_name }}"
  airbyte_{{ catalog_name }}_schema: "{{ catalog_name }}_raw"
