
-- This file was autogenerated with Airbyte Morph. Please do not modify directly.

WITH
addresses AS (
    SELECT * FROM {{ source('recharge', 'addresses') }}
)


SELECT
    addresses.id AS id,
    addresses.customer_id AS customer_id,
    addresses.first_name AS first_name,
    addresses.last_name AS last_name,
    addresses.address1 AS address_1,
    addresses.address2 AS address_2,
    addresses.city AS city,
    addresses.province AS province,
    addresses.country_code AS country_code,
    addresses.zip AS zip,
    addresses.company AS company,
    addresses.phone AS phone,
    addresses.created_at AS created_at,
    addresses.updated_at AS updated_at,
    NULL AS _fivetran_deleted,
    addresses._airbyte_extracted_at AS _fivetran_synced
FROM addresses
