
-- This file was autogenerated with Airbyte Morph. Please do not modify directly.

WITH
orders AS (
    SELECT * FROM {{ source('recharge', 'orders') }}
)


SELECT
    orders.charge_id AS charge_id,
    NULL AS index,
    orders.order_attributes AS order_attribute,
    orders._airbyte_extracted_at AS _fivetran_synced
FROM orders
