
-- This file was autogenerated with Airbyte Morph. Please do not modify directly.

WITH
customers AS (
    SELECT * FROM {{ source('recharge', 'customers') }}
)


SELECT
    customers.id AS id,
    customers.hash AS hash,
    customers.external_customer_id.ecommerce AS external_customer_id_ecommerce,
    customers.email AS email,
    customers.created_at AS created_at,
    customers.updated_at AS updated_at,
    customers.first_charge_processed_at AS first_charge_processed_at,
    customers.first_name AS first_name,
    customers.last_name AS last_name,
    customers.number_active_subscriptions AS subscriptions_active_count,
    customers.number_subscriptions AS subscriptions_total_count,
    customers.has_valid_payment_method AS has_valid_payment_method,
    customers.has_card_error_in_dunning AS has_payment_method_in_dunning,
    customers.tax_exempt AS tax_exempt,
    NULL AS _fivetran_deleted,
    customers._airbyte_extracted_at AS _fivetran_synced
FROM customers
