
-- This file was autogenerated with Airbyte Morph. Please do not modify directly.

WITH
discounts AS (
    SELECT * FROM {{ source('recharge', 'discounts') }}
)


SELECT
    discounts.id AS id,
    discounts.created_at AS created_at,
    discounts.updated_at AS updated_at,
    discounts.starts_at AS starts_at,
    discounts.ends_at AS ends_at,
    discounts.code AS code,
    discounts.value AS value,
    discounts.status AS status,
    discounts.usage_limit AS usage_limits,
    discounts.applies_to AS applies_to,
    discounts.applies_to_resource AS applies_to_resource,
    discounts.applies_to_id AS applies_to_id,
    discounts.applies_to_product_type AS applies_to_product_type,
    discounts.prerequisite_subtotal_min AS minimum_order_amount,
    discounts._airbyte_extracted_at AS _fivetran_synced
FROM discounts
