
-- This file was autogenerated with Airbyte Morph. Please do not modify directly.

WITH
orders AS (
    SELECT * FROM {{ source('recharge', 'orders') }}
)


SELECT
    orders.id AS id,
    orders.customer.id AS customer_id,
    orders.address_id AS address_id,
    orders.charge.id AS charge_id,
    NULL AS is_deleted,
    orders.email AS email,
    orders.transaction_id AS transaction_id,
    orders.charge.status AS charge_status,
    orders.is_prepaid AS is_prepaid,
    orders.status AS status,
    orders.total_price AS total_price,
    orders.type AS type,
    orders.external_order_id.ecommerce AS external_order_id_ecommerce,
    orders.external_order_number.ecommerce AS external_order_number_ecommerce,
    orders.created_at AS created_at,
    orders.updated_at AS updated_at,
    orders.processed_at AS processed_at,
    orders.scheduled_at AS scheduled_at,
    orders.shipped_date AS shipped_date,
    orders._airbyte_extracted_at AS _fivetran_synced
FROM orders
