
-- This file was autogenerated with Airbyte Morph. Please do not modify directly.

WITH
subscriptions AS (
    SELECT * FROM {{ source('recharge', 'subscriptions') }}
)


SELECT
    subscriptions.id AS subscription_id,
    subscriptions.updated_at AS updated_at,
    subscriptions.address_id AS address_id,
    subscriptions.customer_id AS customer_id,
    subscriptions.created_at AS created_at,
    subscriptions.cancelled_at AS cancelled_at,
    subscriptions.next_charge_scheduled_at AS next_charge_scheduled_at,
    subscriptions.price AS price,
    subscriptions.quantity AS quantity,
    subscriptions.cancellation_reason AS cancellation_reason,
    subscriptions.status AS status,
    subscriptions.cancellation_reason_comments AS cancellation_reason_comments,
    subscriptions.product_title AS product_title,
    subscriptions.variant_title AS variant_title,
    subscriptions.external_product_id.ecommerce AS external_product_id_ecommerce,
    subscriptions.external_variant_id.ecommerce AS external_variant_id_ecommerce,
    subscriptions.sku AS sku,
    subscriptions.order_interval_unit AS order_interval_unit,
    subscriptions.order_interval_frequency AS order_interval_frequency,
    subscriptions.charge_interval_frequency AS charge_interval_frequency,
    subscriptions.order_day_of_week AS order_day_of_week,
    subscriptions.order_day_of_month AS order_day_of_month,
    subscriptions.expire_after_specific_number_of_charges AS expire_after_specific_number_of_charges,
    NULL AS _fivetran_deleted,
    subscriptions._airbyte_extracted_at AS _fivetran_synced
FROM subscriptions
