Table "advertiser" {
    "id" varchar [note: 'Advertiser ID']
    "address" varchar [note: 'Advertiser address information']
    "balance" varchar [note: 'Account available balance']
    "cellphone_number" varchar [note: '''Contact mobile number, desensitised data. This is the newest version of the field `phone_number`, which was renamed after the Tiktok Ads v1.3 API release.
    ''']
    "company" varchar [note: 'Advertiser\'s company name']
    "contacter" varchar [note: 'Contact Person']
    "country" varchar [note: 'The advertiser\'s country']
    "create_time" varchar [note: 'Advertiser\'s create time']
    "currency" varchar [note: 'Type of currency used by advertisers']
    "description" varchar [note: 'Brand description, i.e. promotional content']
    "email" varchar [note: 'Advertiser contact email, desensitised data']
    "industry" varchar [note: 'Advertiser industry category']
    "language" varchar [note: 'Language used by advertisers']
    "license_no" varchar [note: 'License number']
    "license_url" varchar [note: 'License preview address, the link is valid for an hour by default.']
    "name" varchar [note: 'Advertiser name']
    "phone_number" varchar [note: '''Contact mobile number, desensitised data. IMPORTANT: This field will not be populated for connectors utilizing the Tiktok Ads v1.3 API version, as the column was renamed.  The new column name is `cellphone_number`.
    ''']
    "promotion_area" varchar [note: 'Operation area']
    "reason" varchar [note: 'Reason for rejection']
    "role" varchar [note: 'Advertiser role']
    "status" varchar [note: 'Advertiser status']
    "telephone" varchar [note: '''Fixed phone number, desensitised data IMPORTANT: This field will not be populated for connectors utilizing the Tiktok Ads v1.3 API version, as the column was renamed.  The new column name is `telephone_number`.
    ''']
    "telephone_number" varchar [note: '''Fixed phone number, desensitised data This is the newest version of the field `telephone`, which was renamed after the Tiktok Ads v1.3 API release.
    ''']
    "timezone" varchar [note: 'Ad account time zone including GMT offset']
    "_fivetran_synced" varchar [note: 'Timestamp of when Fivetran synced a record.']
}

Table "campaign_history" {
    "campaign_id" varchar [note: 'Campaign ID']
    "updated_at" varchar [note: 'Time the record was updated.']
    "advertiser_id" varchar [note: 'Advertiser ID']
    "budget" varchar [note: 'Campaign budget']
    "budget_mode" varchar [note: 'Budget type']
    "campaign_name" varchar [note: 'Campaign name']
    "campaign_type" varchar [note: 'Campaign Type, indicates the campaign is a regular campaign or iOS 14 campaign.']
    "create_time" varchar [note: 'Time at which the campaign was created.']
    "is_new_structure" varchar [note: 'Whether the campaign is a new structure (for the same campaign, the structure of campaign, adgroups and ads are the same)']
    "objective_type" varchar [note: 'Advertising objective.']
    "opt_status" varchar [note: 'Operation status.']
    "status" varchar [note: 'Campaign status']
    "split_test_variable" varchar [note: 'Split Test variables. Optional values; TARGETING, BIDDING_OPTIMIZATION , CREATIVE.']
}

Table "adgroup_history" {
    "adgroup_id" varchar [note: 'Ad group ID']
    "updated_at" varchar [note: 'Time the record was updated.']
    "advertiser_id" varchar [note: 'Advertiser ID']
    "campaign_id" varchar [note: 'The Ad group\'s campaign ID.']
    "action_categories" varchar [note: 'IDs of the action categories (behaviors) that you want to target.']
    "action_days" varchar [note: 'The number of days of the time period to include action from.']
    "adgroup_name" varchar [note: 'Ad group name. Character limit is 512 and cannot contain emoji.']
    "age_groups" varchar [note: '''Age groups you want to target. This is the newest version of the field `age`, which was renamed after the Tiktok Ads v1.3 API release.
    ''']
    "android_osv" varchar [note: 'Minimum Android version.']
    "app_download_url" varchar [note: 'App download link']
    "app_id" varchar [note: 'The Application id of the promoted app']
    "app_name" varchar [note: 'App name.']
    "app_type" varchar [note: 'App type.']
    "audience" varchar [note: 'A list of audience IDs.']
    "audience_type" varchar [note: 'Audience Type']
    "bid" varchar [note: 'CPC, CPM bidding, oCPM learning bidding']
    "bid_type" varchar [note: 'Bidding Strategy']
    "billing_event" varchar [note: 'Bid method.']
    "budget" varchar [note: 'Ad budget. Returns 0.0 when Campaign Budget Optimization (budget_optimize_switch) is on.']
    "budget_mode" varchar [note: 'Budget mode. This field will be ignored when Campaign Budget Optimization (budget_optimize_switch) is enabled.']
    "carriers" varchar [note: 'Carriers that you want to target.']
    "category" varchar [note: 'Ad group category.']
    "click_tracking_url" varchar [note: 'Click monitoring URL.']
    "connection_type" varchar [note: 'Device connection types that you want to target. Default; unlimited.']
    "conversion_bid" varchar [note: 'oCPM conversion bid']
    "cpv_video_duration" varchar [note: '''Video playback duration, required if optimize_goal is VIDEO_VIEW.  Allowed values; SIX_SECONDS (video playback 6s), TWO_SECONDS (video playback 2s)
    ''']
    "creative_material_mode" varchar [note: 'Creative delivery mode.']
    "dayparting" varchar [note: 'Ad delivery period, the default is always and the format is 48 * 7 character string, represented by 0 or 1. > That is, with half an hour as the minimum granularity, a day (24 hours) is divided by the minimum granularity(30 mins) from Monday to Sunday. Resulting in a 48*7 format.0 represents not to be delivered, 1 represents delivery. no transmission, full transmission 0, full transmission 1 all represent full time delivery']
    "deep_bid_type" varchar [note: 'Bidding strategy for in-app events.']
    "deep_cpabid" varchar [note: 'Deep bid']
    "deep_external_action" varchar [note: 'Deep conversion event.']
    "display_name" varchar [note: 'Display name of ad group.']
    "enable_inventory_filter" varchar [note: 'Inventory filtering (Unsafe videos will not be displayed).']
    "excluded_audience" varchar [note: 'A list of audience ID to be excluded.']
    "external_action" varchar [note: 'Conversion event for the ad group. It is required when the promoted object is an app with tracking urls, or when pixel_id is specified.']
    "fallback_type" varchar [note: '''Fallback Type. If the audience do not have the app installed, you can have them fall back to install the app, or to view a specific web page. Not applicable for Deferred Deeplink. Allowed values; APP_INSTALL, WEBSITE, UNSET. If website is chosen, you need to specify the url via landing_page_url field.
    ''']
    "frequency" varchar [note: '''frequency, together with frequency_schedule, controls how often people see your ad (only available for REACH ads).  For example, frequency = 2 frequency_schedule = 3 means "show ads no more than twice every 3 day".
    ''']
    "frequency_schedule" varchar [note: 'frequency, together with frequency, controls how often people see your ad (only available for REACH ads).']
    "gender" varchar [note: 'Gender that you want to target.']
    "impression_tracking_url" varchar [note: 'Display monitoring URL.']
    "interest_category_v2" varchar [note: 'Interest classification. If the interest is specified, users that do not meet interest target will be excluded during delivery.']
    "ios_osv" varchar [note: 'Minimum iOS version.']
    "is_comment_disable" varchar [note: 'Whether to allow comments on your ads on TikTok, Vigo, Helo.']
    "is_hfss" varchar [note: 'Whether the promoted content is HFSS foods (foods that are high in fat, salt, or sugar).']
    "is_new_structure" varchar [note: 'Whether the campaign is a new structure.']
    "keywords" varchar [note: 'Keywords used.']
    "landing_page_url" varchar [note: 'Landing page URL.']
    "languages" varchar [note: 'Codes of the languages that you want to target.']
    "location" varchar [note: 'IDs of the locations that you want to target.']
    "open_url" varchar [note: 'The specific location where you want your audience to go if they have your app installed.']
    "open_url_type" varchar [note: 'The open URL type.']
    "operation_system" varchar [note: 'Device operating systems that you want to target.']
    "opt_status" varchar [note: 'Operation status.']
    "optimize_goal" varchar [note: 'Optimization goal.']
    "pacing" varchar [note: '''You can choose between PACING_MODE_SMOOTH and PACING_MODE_FAST. For PACING_MODE_SMOOTH, the budget is allocated evenly within the scheduled time.  PACING_MODE_FAST would consume budget and produce results as soon as possible. 
    ''']
    "package" varchar [note: 'Package name.']
    "pangle_block_app_list_id" varchar [note: 'Pangle app block list ID.']
    "pixel_id" varchar [note: 'Pixel ID. Only application for landing pages.']
    "placement" varchar [note: 'The apps where you want to deliver your ads.']
    "placement_type" varchar [note: 'Placement type.']
    "profile_image" varchar [note: 'Avatar URL.']
    "schedule_end_time" varchar [note: 'Ad delivery end time (UTC+0). Format should be YYYY-MM-DD HH:MM:SS']
    "schedule_start_time" varchar [note: 'Ad delivery start time (UTC+0). Format should be YYYY-MM-DD HH:MM:SS']
    "schedule_type" varchar [note: 'The schedule type, which can be either SCHEDULE_START_END or SCHEDULE_FROM_NOW.']
    "skip_learning_phase" varchar [note: 'Whether to skip the learning stage.']
    "statistic_type" varchar [note: 'conversion bid statistic type']
    "status" varchar [note: 'Ad group status']
    "video_actions" varchar [note: 'Number of video actions.']
    "video_download" varchar [note: 'Whether users can download your video ads on TikTok(cannot be updated once created).']
}

Table "ad_history" {
    "ad_id" varchar [note: 'Ad ID']
    "updated_at" varchar [note: 'Time the record was updated.']
    "adgroup_id" varchar [note: 'Ad group ID']
    "advertiser_id" varchar [note: 'Advertiser ID']
    "campaign_id" varchar [note: 'Campaign ID']
    "ad_name" varchar [note: 'Ad Name.']
    "ad_text" varchar [note: 'The ad text.']
    "app_name" varchar [note: 'The display name of app download ad.']
    "call_to_action" varchar [note: 'Call to action values.']
    "click_tracking_url" varchar [note: 'Click monitoring URL.']
    "create_time" varchar [note: 'Time at which the ad was created.']
    "display_name" varchar [note: 'The display name of landing page or pure exposure ad.']
    "image_ids" varchar [note: 'A list of image IDs.']
    "impression_tracking_url" varchar [note: 'Display monitoring URL.']
    "is_aco" varchar [note: 'Whether the ad is an automated ad.']
    "is_creative_authorized" varchar [note: '''Whether you grant displaying some of your ads in our TikTok For Business Creative Center. Only valid for non-US advertisers, the default value is false.
    ''']
    "is_new_structure" varchar [note: 'Whether the campaign is a new structure.']
    "landing_page_url" varchar [note: 'Landing page URL.']
    "open_url" varchar [note: 'The specific location where you want your audience to go if they have your app installed.']
    "opt_status" varchar [note: 'Operation status.']
    "playable_url" varchar [note: 'Playable material url.']
    "profile_image" varchar [note: 'Avatar URL.']
    "status" varchar [note: 'Ad status.']
    "video_id" varchar [note: 'The video ID.']
}

Table "ad_report_hourly" {
    "ad_id" varchar [note: 'Ad id']
    "stat_time_hour" varchar [note: 'Hour of activity']
    "cost_per_conversion" varchar [note: '''The average amount of money you\'ve spent on a conversion.  (The total count is calculated based on the time each ad impression occurred.)
    ''']
    "real_time_conversion" varchar [note: '''The number of times your ad achieved an outcome,  based on the objective and settings you selected. (The total count is based on when the conversion actually happened.)
    ''']
    "cpc" varchar [note: 'The average amount of money you\'ve spent on a click.']
    "video_play_actions" varchar [note: 'The number of times your video starts to play. Replays will not be counted.']
    "conversion_rate" varchar [note: '''The percentage of results you received out of all the clicks of your ads.   (The total count is calculated based on the time each ad impression occurred.)
    ''']
    "video_views_p_75" varchar [note: 'The number of times your video was played at 75% of its length. Replays will not be counted.']
    "result" varchar [note: '''The number of times your ad achieved an outcome, based on the optimization goal  you selected. As one campaign may have a number of different optimization goals,  this statistic is not supported for campaigns. Please go to ad groups or ads to view the results.  (The total count is calculated based on the time each ad impression occurred.)
    ''']
    "video_views_p_50" varchar [note: 'The number of times your video was played at 50% of its length. Replays will not be counted.']
    "impressions" varchar [note: 'The number of times your ads were on screen.']
    "comments" varchar [note: 'The number of comments your video creative received within 1 day of a user seeing a paid ad.']
    "real_time_cost_per_result" varchar [note: '''As a campaign may have different optimization goals, the total number of result   is not supported in campaign section now, please go to the ad group section to view the cost per Result. (The total count is based on when the conversion actually happened.)
    ''']
    "conversion" varchar [note: '''The number of times your ad achieved an outcome, based on the secondary goal you selected.  As one campaign may have a number of different secondary goals, this statistic is not supported for campaigns.  Please go to ad groups or ads to view. (The total count is calculated based on the time each ad impression occurred.)
    ''']
    "real_time_result" varchar [note: '''The number of times your ad achieved an outcome, based on the optimization goal you selected.  As a campaign may have different optimization goals, the total number of result is not supported in campaign section now , Please go to the ad group section to view the result. (The total count is based on when the conversion actually happened.)
    ''']
    "video_view_p_100" varchar [note: 'The number of times your video was played at 100% of its length. Replays will not be counted.']
    "shares" varchar [note: 'The number of shares your video creative received within 1 day of a user seeing a paid ad.']
    "real_time_conversion_rate" varchar [note: 'The percentage of results you received out of all the clicks of your ads. (The total count is based on when the conversion actually happened.)']
    "cost_per_secondary_goal_result" varchar [note: '''The average cost for each secondary goal result from your adverts. As one campaign may have a number of different secondary goals,  this statistic is not supported for campaigns. Please go to ad groups or ads to view. (The total count is calculated based on the time each ad impression occurred.)
    ''']
    "secondary_goal_result_rate" varchar [note: '''The percentage of secondary goal results you achieved out of all of the installs of your adverts. As one campaign may have a number  of different secondary goals, this statistic is not supported for campaigns. Please go to ad groups or ads to view. The total count is calculated based on the time each ad impression occurred.
    ''']
    "clicks" varchar [note: 'The number of clicks on your ads.']
    "cost_per_1000_reached" varchar [note: 'The average cost to reach 1,000 unique users. This metric is estimated.']
    "video_views_p_25" varchar [note: 'The number of times your video was played at 25% of its length. Replays will not be counted.']
    "reach" varchar [note: 'The number of unique users who saw your ads at least once. This metric is estimated.']
    "real_time_cost_per_conversion" varchar [note: 'The average amount of money you\'ve spent on a conversion. (The total count is based on when the conversion actually happened.)']
    "profile_visits_rate" varchar [note: 'The rate of profile visits per impression the paid ad drove during the campaign. This metric is only for Boosted TikToks.']
    "average_video_play" varchar [note: 'The average time your video was played per single video view, including any time spent replaying the video.']
    "profile_visits" varchar [note: 'The number of profile visits the ad drove during the campaign. This metric is only for Boosted TikToks.']
    "cpm" varchar [note: 'The average amount of money you\'ve spent per 1,000 impressions.']
    "ctr" varchar [note: 'The percentage of times people saw your ad and performed a click.']
    "video_watched_2_s" varchar [note: 'The number of times your video played for at least 2 seconds. Replays will not be counted.']
    "follows" varchar [note: 'The number of new followers that were gained within 1 day of a user seeing a paid ad. This metric is only for Boosted TikToks.']
    "result_rate" varchar [note: '''The percentage of results you achieved out of all of the views/clicks on your ads. As one campaign may have a number  of different optimization goals, this statistic is not supported for campaigns. Please go to ad groups or ads to view the result rate.  (The total count is calculated based on the time each ad impression occurred.)
    ''']
    "video_watched_6_s" varchar [note: 'The number of times your video played for at least 6 seconds, or completely played. Replays will not be counted.']
    "secondary_goal_result" varchar [note: '''The number of times your ad achieved an outcome, based on the secondary goal you selected. As one campaign may have a number  of different secondary goals, this statistic is not supported for campaigns. Please go to ad groups or ads to view. (The total count is  calculated based on the time each ad impression occurred.)
    ''']
    "cost_per_result" varchar [note: '''The average cost for each result from your ads. As one campaign may have a number of different optimization goals, this statistic  is not supported for campaigns. Please go to ad groups or ads to view the cost per result. (The total count is calculated based on the time each ad impression occurred.)
    ''']
    "average_video_play_per_user" varchar [note: 'The average time your video was played per person, including any time spent replaying the video. This metric is estimated.']
    "real_time_result_rate" varchar [note: 'As a campaign may have different optimization goals, the total number of result is not supported in campaign section now ,Please go to the ad group section to view the Result Rate. (The total count is based on when the conversion actually happened.)']
    "spend" varchar [note: 'The estimated total amount of money you\'ve spent on your campaign, ad group or ad during its schedule.']
    "likes" varchar [note: 'The number of likes your video creative received within 1 day of a user seeing a paid ad.']
    "_fivetran_synced" varchar [note: 'Timestamp of when Fivetran synced a record.']
    "real_time_conversion" varchar [note: 'Number of times your ad resulted in the optimization event you selected.']
    "total_purchase_value" varchar [note: 'The total value of purchase events that occurred in your app that were recorded by your measurement partner.']
    "total_sales_lead_value" varchar [note: 'The monetary worth or potential value assigned to a lead generated through ads.']
}

Table "campaign_report_hourly" {
    "campaign_id" varchar [note: 'Campaign id']
    "stat_time_hour" varchar [note: 'Hour of activity']
    "cost_per_conversion" varchar [note: '''The average amount of money you\'ve spent on a conversion.  (The total count is calculated based on the time each ad impression occurred.)
    ''']
    "real_time_conversion" varchar [note: '''The number of times your ad achieved an outcome,  based on the objective and settings you selected. (The total count is based on when the conversion actually happened.)
    ''']
    "cpc" varchar [note: 'The average amount of money you\'ve spent on a click.']
    "video_play_actions" varchar [note: 'The number of times your video starts to play. Replays will not be counted.']
    "conversion_rate" varchar [note: '''The percentage of results you received out of all the clicks of your ads.   (The total count is calculated based on the time each ad impression occurred.)
    ''']
    "video_views_p_75" varchar [note: 'The number of times your video was played at 75% of its length. Replays will not be counted.']
    "result" varchar [note: '''The number of times your ad achieved an outcome, based on the optimization goal  you selected. As one campaign may have a number of different optimization goals,  this statistic is not supported for campaigns. Please go to ad groups or ads to view the results.  (The total count is calculated based on the time each ad impression occurred.)
    ''']
    "video_views_p_50" varchar [note: 'The number of times your video was played at 50% of its length. Replays will not be counted.']
    "impressions" varchar [note: 'The number of times your ads were on screen.']
    "comments" varchar [note: 'The number of comments your video creative received within 1 day of a user seeing a paid ad.']
    "real_time_cost_per_result" varchar [note: '''As a campaign may have different optimization goals, the total number of result  is not supported in campaign section now, please go to the ad group section to view the cost  per Result. (The total count is based on when the conversion actually happened.)
    ''']
    "conversion" varchar [note: '''The number of times your ad achieved an outcome, based on the secondary goal you selected.  As one campaign may have a number of different secondary goals, this statistic is not supported for campaigns. Please go to ad groups or ads to view. (The total count is calculated based on the time each ad impression occurred.)
    ''']
    "real_time_result" varchar [note: '''The number of times your ad achieved an outcome, based on the optimization goal you selected.  As a campaign may have different optimization goals, the total number of result is not supported in campaign section now , Please go to the ad group section to view the result. (The total count is based on when the conversion actually happened.)
    ''']
    "video_view_p_100" varchar [note: 'The number of times your video was played at 100% of its length. Replays will not be counted.']
    "shares" varchar [note: 'The number of shares your video creative received within 1 day of a user seeing a paid ad.']
    "real_time_conversion_rate" varchar [note: 'The percentage of results you received out of all the clicks of your ads. (The total count is based on when the conversion actually happened.)']
    "cost_per_secondary_goal_result" varchar [note: '''The average cost for each secondary goal result from your adverts. As one campaign may have a number of different secondary goals,  this statistic is not supported for campaigns. Please go to ad groups or ads to view. (The total count is calculated based on the time each ad impression occurred.)
    ''']
    "secondary_goal_result_rate" varchar [note: '''The percentage of secondary goal results you achieved out of all of the installs of your adverts. As one campaign may have a number  of different secondary goals, this statistic is not supported for campaigns. Please go to ad groups or ads to view. The total count is calculated based on the time each ad impression occurred.
    ''']
    "clicks" varchar [note: 'The number of clicks on your ads.']
    "cost_per_1000_reached" varchar [note: 'The average cost to reach 1,000 unique users. This metric is estimated.']
    "video_views_p_25" varchar [note: 'The number of times your video was played at 25% of its length. Replays will not be counted.']
    "reach" varchar [note: 'The number of unique users who saw your ads at least once. This metric is estimated.']
    "real_time_cost_per_conversion" varchar [note: 'The average amount of money you\'ve spent on a conversion. (The total count is based on when the conversion actually happened.)']
    "profile_visits_rate" varchar [note: 'The rate of profile visits per impression the paid ad drove during the campaign. This metric is only for Boosted TikToks.']
    "average_video_play" varchar [note: 'The average time your video was played per single video view, including any time spent replaying the video.']
    "profile_visits" varchar [note: 'The number of profile visits the ad drove during the campaign. This metric is only for Boosted TikToks.']
    "cpm" varchar [note: 'The average amount of money you\'ve spent per 1,000 impressions.']
    "ctr" varchar [note: 'The percentage of times people saw your ad and performed a click.']
    "video_watched_2_s" varchar [note: 'The number of times your video played for at least 2 seconds. Replays will not be counted.']
    "follows" varchar [note: 'The number of new followers that were gained within 1 day of a user seeing a paid ad. This metric is only for Boosted TikToks.']
    "result_rate" varchar [note: '''The percentage of results you achieved out of all of the views/clicks on your ads. As one campaign may have a number  of different optimization goals, this statistic is not supported for campaigns. Please go to ad groups or ads to view the result rate.  (The total count is calculated based on the time each ad impression occurred.)
    ''']
    "video_watched_6_s" varchar [note: 'The number of times your video played for at least 6 seconds, or completely played. Replays will not be counted.']
    "secondary_goal_result" varchar [note: '''The number of times your ad achieved an outcome, based on the secondary goal you selected. As one campaign may have a number  of different secondary goals, this statistic is not supported for campaigns. Please go to ad groups or ads to view. (The total count is  calculated based on the time each ad impression occurred.)
    ''']
    "cost_per_result" varchar [note: '''The average cost for each result from your ads. As one campaign may have a number of different optimization goals, this statistic  is not supported for campaigns. Please go to ad groups or ads to view the cost per result. (The total count is calculated based on the time each ad impression occurred.)
    ''']
    "average_video_play_per_user" varchar [note: 'The average time your video was played per person, including any time spent replaying the video. This metric is estimated.']
    "real_time_result_rate" varchar [note: '''As a campaign may have different optimization goals, the total number of result is not supported in campaign section now ,Please go to the ad group section to  view the Result Rate. (The total count is based on when the conversion actually happened.)
    ''']
    "spend" varchar [note: 'The estimated total amount of money you\'ve spent on your campaign, ad group or ad during its schedule.']
    "likes" varchar [note: 'The number of likes your video creative received within 1 day of a user seeing a paid ad.']
    "_fivetran_synced" varchar [note: 'Timestamp of when Fivetran synced a record.']
    "real_time_conversion" varchar [note: 'Number of times your ad resulted in the optimization event you selected.']
    "total_purchase_value" varchar [note: 'The total value of purchase events that occurred in your app that were recorded by your measurement partner.']
    "total_sales_lead_value" varchar [note: 'The monetary worth or potential value assigned to a lead generated through ads.']
}

Table "adgroup_report_hourly" {
    "adgroup_id" varchar [note: 'Ad group id']
    "stat_time_hour" varchar [note: 'Hour of activity']
    "cost_per_conversion" varchar [note: '''The average amount of money you\'ve spent on a conversion.  (The total count is calculated based on the time each ad impression occurred.)
    ''']
    "real_time_conversion" varchar [note: '''The number of times your ad achieved an outcome,  based on the objective and settings you selected. (The total count is based on when the conversion actually happened.)
    ''']
    "cpc" varchar [note: 'The average amount of money you\'ve spent on a click.']
    "video_play_actions" varchar [note: 'The number of times your video starts to play. Replays will not be counted.']
    "conversion_rate" varchar [note: 'The percentage of results you received out of all the clicks of your ads. (The total count is calculated based on the time each ad impression occurred.)']
    "video_views_p_75" varchar [note: 'The number of times your video was played at 75% of its length. Replays will not be counted.']
    "result" varchar [note: '''The number of times your ad achieved an outcome, based on the optimization goal  you selected. As one campaign may have a number of different optimization goals,  this statistic is not supported for campaigns. Please go to ad groups or ads to view the results.  (The total count is calculated based on the time each ad impression occurred.)
    ''']
    "video_views_p_50" varchar [note: 'The number of times your video was played at 50% of its length. Replays will not be counted.']
    "impressions" varchar [note: 'The number of times your ads were on screen.']
    "comments" varchar [note: 'The number of comments your video creative received within 1 day of a user seeing a paid ad.']
    "real_time_cost_per_result" varchar [note: '''As a campaign may have different optimization goals, the total number of result  is not supported in campaign section now, please go to the ad group section to view the cost  per Result. (The total count is based on when the conversion actually happened.)
    ''']
    "conversion" varchar [note: '''The number of times your ad achieved an outcome, based on the secondary goal you selected.  As one campaign may have a number of different secondary goals, this statistic is not supported for campaigns.  Please go to ad groups or ads to view. (The total count is calculated based on the time each ad impression occurred.)
    ''']
    "real_time_result" varchar [note: '''The number of times your ad achieved an outcome, based on the optimization goal you selected.  As a campaign may have different optimization goals, the total number of result is not supported in campaign section now , Please go to the ad group section to view the result. (The total count is based on when the conversion actually happened.)
    ''']
    "video_view_p_100" varchar [note: 'The number of times your video was played at 100% of its length. Replays will not be counted.']
    "shares" varchar [note: 'The number of shares your video creative received within 1 day of a user seeing a paid ad.']
    "real_time_conversion_rate" varchar [note: 'The percentage of results you received out of all the clicks of your ads. (The total count is based on when the conversion actually happened.)']
    "cost_per_secondary_goal_result" varchar [note: '''The average cost for each secondary goal result from your adverts. As one campaign may have a number of different secondary goals,  this statistic is not supported for campaigns. Please go to ad groups or ads to view. (The total count is calculated based on the time each ad impression occurred.)
    ''']
    "secondary_goal_result_rate" varchar [note: '''The percentage of secondary goal results you achieved out of all of the installs of your adverts. As one campaign may have a number  of different secondary goals, this statistic is not supported for campaigns. Please go to ad groups or ads to view. The total count is calculated based on the time each ad impression occurred.
    ''']
    "clicks" varchar [note: 'The number of clicks on your ads.']
    "cost_per_1000_reached" varchar [note: 'The average cost to reach 1,000 unique users. This metric is estimated.']
    "video_views_p_25" varchar [note: 'The number of times your video was played at 25% of its length. Replays will not be counted.']
    "reach" varchar [note: 'The number of unique users who saw your ads at least once. This metric is estimated.']
    "real_time_cost_per_conversion" varchar [note: 'The average amount of money you\'ve spent on a conversion. (The total count is based on when the conversion actually happened.)']
    "profile_visits_rate" varchar [note: 'The rate of profile visits per impression the paid ad drove during the campaign. This metric is only for Boosted TikToks.']
    "average_video_play" varchar [note: 'The average time your video was played per single video view, including any time spent replaying the video.']
    "profile_visits" varchar [note: 'The number of profile visits the ad drove during the campaign. This metric is only for Boosted TikToks.']
    "cpm" varchar [note: 'The average amount of money you\'ve spent per 1,000 impressions.']
    "ctr" varchar [note: 'The percentage of times people saw your ad and performed a click.']
    "video_watched_2_s" varchar [note: 'The number of times your video played for at least 2 seconds. Replays will not be counted.']
    "follows" varchar [note: 'The number of new followers that were gained within 1 day of a user seeing a paid ad. This metric is only for Boosted TikToks.']
    "result_rate" varchar [note: '''The percentage of results you achieved out of all of the views/clicks on your ads. As one campaign may have a number  of different optimization goals, this statistic is not supported for campaigns. Please go to ad groups or ads to view the result rate.  (The total count is calculated based on the time each ad impression occurred.)
    ''']
    "video_watched_6_s" varchar [note: 'The number of times your video played for at least 6 seconds, or completely played. Replays will not be counted.']
    "secondary_goal_result" varchar [note: '''The number of times your ad achieved an outcome, based on the secondary goal you selected. As one campaign may have a number  of different secondary goals, this statistic is not supported for campaigns. Please go to ad groups or ads to view. (The total count is  calculated based on the time each ad impression occurred.)
    ''']
    "cost_per_result" varchar [note: '''The average cost for each result from your ads. As one campaign may have a number of different optimization goals, this statistic  is not supported for campaigns. Please go to ad groups or ads to view the cost per result. (The total count is calculated based on the time each ad impression occurred.)
    ''']
    "average_video_play_per_user" varchar [note: 'The average time your video was played per person, including any time spent replaying the video. This metric is estimated.']
    "real_time_result_rate" varchar [note: '''As a campaign may have different optimization goals, the total number of result is not supported in campaign section now ,Please go to the ad group section to view the Result Rate.  (The total count is based on when the conversion actually happened.)
    ''']
    "spend" varchar [note: 'The estimated total amount of money you\'ve spent on your campaign, ad group or ad during its schedule.']
    "likes" varchar [note: 'The number of likes your video creative received within 1 day of a user seeing a paid ad.']
    "_fivetran_synced" varchar [note: 'Timestamp of when Fivetran synced a record.']
    "real_time_conversion" varchar [note: 'Number of times your ad resulted in the optimization event you selected.']
    "total_purchase_value" varchar [note: 'The total value of purchase events that occurred in your app that were recorded by your measurement partner.']
    "total_sales_lead_value" varchar [note: 'The monetary worth or potential value assigned to a lead generated through ads.']
}