default:
  target: duckdb
  outputs:
    duckdb:
      type: duckdb
      # Assume we are running from `catalog/{source-name}/dbt_project/`
      # and that repo root is 3 levels up.
      path: ../../../.data/iterable.duckdb
      extensions:
        - httpfs
        - parquet
    motherduck:
      type: duckdb
      path: "md:airbyte_iterable"
      extensions:
        - httpfs
        - parquet
      settings:
        motherduck_token: ${MOTHERDUCK_TOKEN}
