
-- This file was autogenerated with Airbyte Morph. Please do not modify directly.

WITH
issue_comments AS (
    SELECT * FROM {{ source('jira', 'issue_comments') }}
)


SELECT
    issue_comments.id AS id,
    issue_comments.author AS author_id,
    issue_comments.body AS body,
    issue_comments.created AS created,
    issue_comments.jsdPublic AS is_public,
    issue_comments.issueId AS issue_id,
    issue_comments.updateAuthor AS update_author_id,
    issue_comments.updated AS updated
FROM issue_comments
