
-- This file was autogenerated with Airbyte Morph. Please do not modify directly.

WITH
project_components AS (
    SELECT * FROM {{ source('jira', 'project_components') }}
)


SELECT
    project_components.id AS id,
    project_components.description AS description,
    project_components.name AS name,
    project_components.projectId AS project_id
FROM project_components
