
-- This file was autogenerated with Airbyte Morph. Please do not modify directly.

WITH
issue_custom_field_options AS (
    SELECT * FROM {{ source('jira', 'issue_custom_field_options') }}
)


SELECT
    issue_custom_field_options.fieldId AS field_id,
    NULL AS issue_id,
    issue_custom_field_options._airbyte_extracted_at AS time,
    issue_custom_field_options.value AS value
FROM issue_custom_field_options
