
-- This file was autogenerated with Airbyte Morph. Please do not modify directly.

WITH
issues AS (
    SELECT * FROM {{ source('jira', 'issues') }}
)


SELECT
    issues.id AS id,
    NULL AS _fivetran_deleted,
    issues.fields.assignee.accountId AS assignee,
    issues.fields.created AS created,
    issues.fields.creator.accountId AS creator,
    issues.fields.description.content AS description,
    issues.fields.duedate AS due_date,
    issues.fields.environment AS environment,
    issues.fields.issuetype.id AS issue_type,
    issues.key AS key,
    issues.fields.lastViewed AS last_viewed,
    issues.fields.timeoriginalestimate AS original_estimate,
    NULL AS parent_id,
    issues.fields.priority.id AS priority,
    issues.fields.project.id AS project,
    issues.fields.timeestimate AS remaining_estimate,
    issues.fields.reporter.accountId AS reporter,
    issues.fields.resolution.id AS resolution,
    issues.fields.resolutiondate AS resolved,
    issues.fields.status.id AS status,
    issues.fields.statuscategorychangedate AS status_category_changed,
    issues.fields.summary AS summary,
    issues.fields.timespent AS time_spent,
    issues.fields.updated AS updated,
    issues.fields.workratio AS work_ratio
FROM issues
