
-- This file was autogenerated with Airbyte Morph. Please do not modify directly.

WITH
issue_types AS (
    SELECT * FROM {{ source('jira', 'issue_types') }}
)


SELECT
    issue_types.id AS id,
    issue_types.description AS description,
    issue_types.name AS name,
    issue_types.subtask AS subtask
FROM issue_types
