
-- This file was autogenerated with Airbyte Morph. Please do not modify directly.

WITH
issue_priorities AS (
    SELECT * FROM {{ source('jira', 'issue_priorities') }}
)


SELECT
    issue_priorities.id AS id,
    issue_priorities.description AS description,
    issue_priorities.name AS name
FROM issue_priorities
