
-- This file was autogenerated with Airbyte Morph. Please do not modify directly.

WITH
projects AS (
    SELECT * FROM {{ source('jira', 'projects') }}
)


SELECT
    projects.id AS id,
    projects.description AS description,
    projects.key AS key,
    NULL AS lead_id,
    projects.name AS name,
    NULL AS permission_scheme_id,
    projects.projectCategory AS project_category_id,
    projects.projectTypeKey AS project_type_key
FROM projects
