
-- This file was autogenerated with Airbyte Morph. Please do not modify directly.

WITH
issue_resolutions AS (
    SELECT * FROM {{ source('jira', 'issue_resolutions') }}
)


SELECT
    issue_resolutions.id AS id,
    issue_resolutions.description AS description,
    issue_resolutions.name AS name
FROM issue_resolutions
