
-- This file was autogenerated with Airbyte Morph. Please do not modify directly.

WITH
sprints AS (
    SELECT * FROM {{ source('jira', 'sprints') }}
)


SELECT
    sprints.id AS id,
    sprints.boardId AS board_id,
    sprints.completeDate AS complete_date,
    sprints.endDate AS end_date,
    sprints.name AS name,
    sprints.startDate AS start_date
FROM sprints
