
-- This file was autogenerated with Airbyte Morph. Please do not modify directly.

WITH
workflow_statuses AS (
    SELECT * FROM {{ source('jira', 'workflow_statuses') }}
)


SELECT
    workflow_statuses.id AS id,
    workflow_statuses.description AS description,
    workflow_statuses.name AS name,
    workflow_statuses.statusCategory.id AS status_category_id
FROM workflow_statuses
