
-- This file was autogenerated with Airbyte Morph. Please do not modify directly.

WITH
workflow_status_categories AS (
    SELECT * FROM {{ source('jira', 'workflow_status_categories') }}
)


SELECT
    workflow_status_categories.id AS id,
    workflow_status_categories.name AS name
FROM workflow_status_categories
