
-- This file was autogenerated with Airbyte Morph. Please do not modify directly.

WITH
users AS (
    SELECT * FROM {{ source('jira', 'users') }}
)


SELECT
    users.accountId AS id,
    users.emailAddress AS email,
    users.locale AS locale,
    users.name AS name,
    users.timeZone AS time_zone,
    users.key AS username
FROM users
