
-- This file was autogenerated with Airbyte Morph. Please do not modify directly.

WITH
project_versions AS (
    SELECT * FROM {{ source('jira', 'project_versions') }}
)


SELECT
    project_versions.archived AS archived,
    project_versions.description AS description,
    project_versions.id AS id,
    project_versions.name AS name,
    project_versions.overdue AS overdue,
    project_versions.projectId AS project_id,
    project_versions.releaseDate AS release_date,
    project_versions.released AS released,
    project_versions.startDate AS start_date
FROM project_versions
