[project]
source_name = "hubspot"
project_name = "fivetran-interop"
generated_at = "2025-03-24T18:18:42Z"
requirements_file = "requirements/fivetran-interop/src_hubspot.yml"
requirements_file_hash = "e64baeee0fecf68e9ce3084b0ae8d7a28a69e45ea1d1a9d881e9963bf5eb685a"
airbyte_source_file = "generated/airbyte-catalog.json"
airbyte_source_file_hash = "0e99e803a447faf66c7dd559a4035d9aeee220bb09db019e5434604ae41f6d22"

[coverage]
unused_source_streams = []
unmapped_target_tables = []

[mappings.contact]
source_file = "contact.yml"
source_file_hash = "c01860d960e4d4287e4c0d3939c5b81272afde6287af507eaadb798c68d6d926"
unmapped_target_fields = []

[mappings.contact.unused_source_fields]
contacts = [
    "companies",
    "createdAt",
    "properties",
    "updatedAt",
]

[mappings.company]
source_file = "company.yml"
source_file_hash = "ffcae37de6c2efcd09fd61f000ce561c152388ea73e3317a9bde18d19c86a65b"
unmapped_target_fields = []

[mappings.company.unused_source_fields]
companies = [
    "contacts",
    "createdAt",
    "properties",
    "properties_about_us",
    "properties_closedate",
    "properties_custom_company_property",
    "properties_days_to_close",
    "properties_domain",
    "properties_engagements_last_meeting_booked",
    "properties_engagements_last_meeting_booked_campaign",
    "properties_engagements_last_meeting_booked_medium",
    "properties_engagements_last_meeting_booked_source",
    "properties_facebook_company_page",
    "properties_facebookfans",
    "properties_first_contact_createdate",
    "properties_first_contact_createdate_timestamp_earliest_value_78b50eea",
    "properties_first_conversion_date",
    "properties_first_conversion_event_name",
    "properties_first_deal_created_date",
    "properties_founded_year",
    "properties_googleplus_page",
    "properties_hs_additional_domains",
    "properties_hs_all_accessible_team_ids",
    "properties_hs_all_owner_ids",
    "properties_hs_all_team_ids",
    "properties_hs_analytics_first_timestamp",
    "properties_hs_analytics_first_touch_converting_campaign",
    "properties_hs_analytics_first_visit_timestamp",
    "properties_hs_analytics_last_timestamp",
    "properties_hs_analytics_last_timestamp_timestamp_latest_value_4e16365a",
    "properties_hs_analytics_last_touch_converting_campaign",
    "properties_hs_analytics_last_touch_converting_campaign_timestamp_latest_value_81a64e30",
    "properties_hs_analytics_last_visit_timestamp",
    "properties_hs_analytics_last_visit_timestamp_timestamp_latest_value_999a0fce",
    "properties_hs_analytics_latest_source",
    "properties_hs_analytics_latest_source_data_1",
    "properties_hs_analytics_latest_source_data_2",
    "properties_hs_analytics_latest_source_timestamp",
    "properties_hs_analytics_num_page_views",
    "properties_hs_analytics_num_page_views_cardinality_sum_e46e85b0",
    "properties_hs_analytics_num_visits",
    "properties_hs_analytics_num_visits_cardinality_sum_53d952a6",
    "properties_hs_analytics_source",
    "properties_hs_analytics_source_data_1",
    "properties_hs_analytics_source_data_2",
    "properties_hs_annual_revenue_currency_code",
    "properties_hs_avatar_filemanager_key",
    "properties_hs_country_code",
    "properties_hs_created_by_user_id",
    "properties_hs_createdate",
    "properties_hs_csm_sentiment",
    "properties_hs_customer_success_ticket_sentiment",
    "properties_hs_date_entered_customer",
    "properties_hs_date_entered_evangelist",
    "properties_hs_date_entered_lead",
    "properties_hs_date_entered_marketingqualifiedlead",
    "properties_hs_date_entered_opportunity",
    "properties_hs_date_entered_other",
    "properties_hs_date_entered_salesqualifiedlead",
    "properties_hs_date_entered_subscriber",
    "properties_hs_date_exited_customer",
    "properties_hs_date_exited_evangelist",
    "properties_hs_date_exited_lead",
    "properties_hs_date_exited_marketingqualifiedlead",
    "properties_hs_date_exited_opportunity",
    "properties_hs_date_exited_other",
    "properties_hs_date_exited_salesqualifiedlead",
    "properties_hs_date_exited_subscriber",
    "properties_hs_employee_range",
    "properties_hs_ideal_customer_profile",
    "properties_hs_industry_group",
    "properties_hs_is_enriched",
    "properties_hs_is_target_account",
    "properties_hs_keywords",
    "properties_hs_last_booked_meeting_date",
    "properties_hs_last_logged_call_date",
    "properties_hs_last_logged_outgoing_email_date",
    "properties_hs_last_metered_enrichment_timestamp",
    "properties_hs_last_open_task_date",
    "properties_hs_last_sales_activity_date",
    "properties_hs_last_sales_activity_timestamp",
    "properties_hs_last_sales_activity_type",
    "properties_hs_lastmodifieddate",
    "properties_hs_latest_createdate_of_active_subscriptions",
    "properties_hs_latest_meeting_activity",
    "properties_hs_lead_status",
    "properties_hs_linkedin_handle",
    "properties_hs_logo_url",
    "properties_hs_merged_object_ids",
    "properties_hs_notes_last_activity",
    "properties_hs_notes_next_activity_type",
    "properties_hs_num_blockers",
    "properties_hs_num_child_companies",
    "properties_hs_num_contacts_with_buying_roles",
    "properties_hs_num_decision_makers",
    "properties_hs_num_open_deals",
    "properties_hs_object_id",
    "properties_hs_object_source",
    "properties_hs_object_source_detail_1",
    "properties_hs_object_source_detail_2",
    "properties_hs_object_source_detail_3",
    "properties_hs_object_source_id",
    "properties_hs_object_source_label",
    "properties_hs_object_source_user_id",
    "properties_hs_parent_company_id",
    "properties_hs_pinned_engagement_id",
    "properties_hs_pipeline",
    "properties_hs_predictivecontactscore_v2",
    "properties_hs_predictivecontactscore_v2_next_max_max_d4e58c1e",
    "properties_hs_quick_context",
    "properties_hs_read_only",
    "properties_hs_revenue_range",
    "properties_hs_sales_email_last_replied",
    "properties_hs_shared_team_ids",
    "properties_hs_shared_user_ids",
    "properties_hs_target_account",
    "properties_hs_target_account_probability",
    "properties_hs_target_account_recommendation_snooze_time",
    "properties_hs_target_account_recommendation_state",
    "properties_hs_task_label",
    "properties_hs_time_in_customer",
    "properties_hs_time_in_evangelist",
    "properties_hs_time_in_lead",
    "properties_hs_time_in_marketingqualifiedlead",
    "properties_hs_time_in_opportunity",
    "properties_hs_time_in_other",
    "properties_hs_time_in_salesqualifiedlead",
    "properties_hs_time_in_subscriber",
    "properties_hs_total_deal_value",
    "properties_hs_unique_creation_key",
    "properties_hs_updated_by_user_id",
    "properties_hs_user_ids_of_all_notification_followers",
    "properties_hs_user_ids_of_all_notification_unfollowers",
    "properties_hs_user_ids_of_all_owners",
    "properties_hs_was_imported",
    "properties_hubspot_owner_assigneddate",
    "properties_hubspot_owner_id",
    "properties_hubspot_team_id",
    "properties_hubspotscore",
    "properties_is_public",
    "properties_lifecyclestage",
    "properties_linkedin_company_page",
    "properties_linkedinbio",
    "properties_notes_last_contacted",
    "properties_notes_last_updated",
    "properties_notes_next_activity_date",
    "properties_num_associated_contacts",
    "properties_num_associated_deals",
    "properties_num_contacted_notes",
    "properties_num_conversion_events",
    "properties_num_conversion_events_cardinality_sum_d095f14b",
    "properties_num_notes",
    "properties_numberofemployees",
    "properties_phone",
    "properties_recent_conversion_date",
    "properties_recent_conversion_date_timestamp_latest_value_72856da1",
    "properties_recent_conversion_event_name",
    "properties_recent_conversion_event_name_timestamp_latest_value_66c820bf",
    "properties_recent_deal_amount",
    "properties_recent_deal_close_date",
    "properties_timezone",
    "properties_total_money_raised",
    "properties_total_revenue",
    "properties_twitterbio",
    "properties_twitterfollowers",
    "properties_twitterhandle",
    "properties_type",
    "properties_web_technologies",
    "properties_website",
    "properties_zip",
    "updatedAt",
]

[mappings.deal]
source_file = "deal.yml"
source_file_hash = "25d2d66794ce3a53d66ddac8655dc8cc02b0a9c1587addfd9c92b6d3366f5008"
unmapped_target_fields = []

[mappings.deal.unused_source_fields]
deals = [
    "companies",
    "contacts",
    "createdAt",
    "line_items",
    "properties",
    "updatedAt",
]
