project_id: recurly.fivetran-interop
source_name: recurly
# Target schema file snapshotted from: https://github.com/fivetran/dbt_recurly_source/blob/main/models/src_recurly.yml
target_dbt_schema_url: https://raw.githubusercontent.com/fivetran/dbt_recurly_source/refs/heads/main/models/src_recurly.yml
# SQL dialect configuration
sql_dialect: duckdb
subcolumn_traversal: dot_notation