[project]
source_name = "facebook_marketing"
project_name = "fivetran-interop"
generated_at = "2025-03-26T22:27:58Z"
requirements_file = "requirements/fivetran-interop/src_hubspot.yml"
requirements_file_hash = ""
airbyte_source_file = "generated/src_airbyte_hubspot.yml"
airbyte_source_file_hash = ""

[coverage]
unused_source_streams = [
    "activities",
    "ads_insights",
    "ads_insights_action_carousel_card",
    "ads_insights_action_conversion_device",
    "ads_insights_action_product_id",
    "ads_insights_action_reaction",
    "ads_insights_action_video_sound",
    "ads_insights_action_video_type",
    "ads_insights_age_and_gender",
    "ads_insights_country",
    "ads_insights_delivery_device",
    "ads_insights_delivery_platform",
    "ads_insights_delivery_platform_and_device_platform",
    "ads_insights_demographics_age",
    "ads_insights_demographics_country",
    "ads_insights_demographics_dma_region",
    "ads_insights_demographics_gender",
    "ads_insights_dma",
    "ads_insights_platform_and_device",
    "ads_insights_region",
    "custom_audiences",
    "custom_conversions",
    "customcustom_insight_stream",
    "images",
    "videos",
]
unmapped_target_tables = []

[mappings.account_history]
source_file = "account_history.yml"
source_file_hash = "ae310628d0e6f315116ddbfc3fd48bc251466d5858382985663bc1d9c1d7db11"
unmapped_target_fields = []
omitted_target_fields = []

[mappings.account_history.mapped_target_fields]
id = "ad_account.id"
name = "ad_account.name"
_fivetran_synced = "_airbyte_extracted_at"
account_status = "ad_account.account_status"
business_country_code = "ad_account.business_country_code"
created_time = "ad_account.created_time"
currency = "ad_account.currency"
timezone_name = "ad_account.timezone_name"

[mappings.account_history.unused_source_fields]
ad_account = [
    "account_id",
    "age",
    "amount_spent",
    "balance",
    "business",
    "business_city",
    "business_name",
    "business_state",
    "business_street",
    "business_street2",
    "business_zip",
    "can_create_brand_lift_study",
    "capabilities",
    "disable_reason",
    "end_advertiser",
    "end_advertiser_name",
    "extended_credit_invoice_group",
    "failed_delivery_checks",
    "fb_entity",
    "funding_source",
    "funding_source_details",
    "has_migrated_permissions",
    "io_number",
    "is_attribution_spec_system_default",
    "is_direct_deals_enabled",
    "is_in_3ds_authorization_enabled_market",
    "is_notifications_enabled",
    "is_personal",
    "is_prepay_account",
    "is_tax_id_required",
    "line_numbers",
    "media_agency",
    "min_campaign_group_spend_cap",
    "min_daily_budget",
    "offsite_pixels_tos_accepted",
    "owner",
    "partner",
    "rf_spec",
    "spend_cap",
    "tax_id",
    "tax_id_status",
    "tax_id_type",
    "timezone_id",
    "timezone_offset_hours_utc",
    "tos_accepted",
    "user_tasks",
    "user_tos_accepted",
    "_airbyte_meta",
    "_airbyte_raw_id",
]

[mappings.ad_history]
source_file = "ad_history.yml"
source_file_hash = "73743ccfa74179caaa95c05144787ea8cd054427f117c8fcaa35b724650fae5f"
unmapped_target_fields = []
omitted_target_fields = []

[mappings.ad_history.mapped_target_fields]
_fivetran_synced = "ads._airbyte_extracted_at"
account_id = "ads.account_id"
ad_set_id = "ads.adset_id"
campaign_id = "ads.campaign_id"
conversion_domain = "ads.conversion_specs"
creative_id = "ads.creative"
id = "ads.id"
name = "ads.name"
updated_time = "ads.updated_time"

[mappings.ad_history.unused_source_fields]

[mappings.ad_set_history]
source_file = "ad_set_history.yml"
source_file_hash = "2e00f30f0a557ce9bd1fb4d9bfc18d54fc456a3aead8a01e73aaeaa57b420803"
unmapped_target_fields = [
    "optimization_goal",
    "status",
]
omitted_target_fields = []

[mappings.ad_set_history.mapped_target_fields]
id = "ad_sets.id"
account_id = "ad_sets.account_id"
campaign_id = "ad_sets.campaign_id"
name = "ad_sets.name"
_fivetran_synced = "_airbyte_extracted_at"
updated_time = "ad_sets.updated_time"
start_time = "ad_sets.start_time"
end_time = "ad_sets.end_time"
bid_strategy = "ad_sets.bid_strategy"
daily_budget = "ad_sets.daily_budget"
budget_remaining = "ad_sets.budget_remaining"

[mappings.ad_set_history.unused_source_fields]
ad_sets = [
    "promoted_object",
    "created_time",
    "lifetime_budget",
    "targeting",
    "bid_info",
    "bid_amount",
    "bid_constraints",
    "adlabels",
    "learning_stage_info",
    "effective_status",
    "_airbyte_meta",
    "_airbyte_raw_id",
]

[mappings.basic_ad]
source_file = "basic_ad.yml"
source_file_hash = "49c060c8e6457aef05962b997d545c537addbbbf8e8f516e10b7084758fa2463"
unmapped_target_fields = [
    "adset_name",
    "date",
    "inline_link_clicks",
]
omitted_target_fields = []

[mappings.basic_ad.mapped_target_fields]
ad_id = "ads_insights.ad_id"
ad_name = "ads_insights.ad_name"
account_id = "ads_insights.account_id"
impressions = "ads_insights.impressions"
spend = "ads_insights.spend"
reach = "ads_insights.reach"
frequency = "ads_insights.frequency"
_fivetran_synced = "_airbyte_extracted_at"

[mappings.basic_ad.unused_source_fields]
ads_insights = [
    "account_currency",
    "account_name",
    "action_values",
    "actions",
    "ad_click_actions",
    "ad_impression_actions",
    "adset_id",
    "_airbyte_meta",
    "_airbyte_raw_id",
]

[mappings.basic_ad_action_values]
source_file = "basic_ad_action_values.yml"
source_file_hash = "7bc7a7a4ebf886a74fd0760f3feb718e38ad73c4b6fb2906f683b5d9c581fe53"
unmapped_target_fields = [
    "_7_d_click",
    "_fivetran_id",
    "date",
    "index",
]
omitted_target_fields = []

[mappings.basic_ad_action_values.mapped_target_fields]
_fivetran_synced = "_airbyte_extracted_at"
action_type = "ads_insights_action_type.action_type"
ad_id = "ads_insights_action_type.ad_id"
value = "ads_insights_action_type.value"

[mappings.basic_ad_action_values.unused_source_fields]
ads_insights_action_type = [
    "_airbyte_meta",
    "_airbyte_raw_id",
    "account_id",
    "account_name",
    "action_destination",
    "action_target_id",
    "action_attribution_windows",
    "action_carousel_card_id",
    "action_carousel_card_name",
    "action_converted_product_id",
    "action_device",
    "action_event_channel",
    "action_reaction",
    "action_video_sound",
    "action_video_type",
    "ad_name",
    "adset_id",
    "adset_name",
    "campaign_id",
    "campaign_name",
    "inline_link_clicks",
    "objective",
]

[mappings.basic_ad_actions]
source_file = "basic_ad_actions.yml"
source_file_hash = "b5d9a40441cebdda5374e2a1b3e62fe0956ec022349c3566bea6ed6cb2677da0"
unmapped_target_fields = [
    "_1_d_view",
    "_28_d_click",
    "_7_d_click",
    "_fivetran_id",
    "date",
    "index",
    "inline",
]
omitted_target_fields = []

[mappings.basic_ad_actions.mapped_target_fields]
_fivetran_synced = "_airbyte_extracted_at"
action_type = "ads_insights_action_type.action_type"
ad_id = "ads_insights_action_type.ad_id"
value = "ads_insights_action_type.value"

[mappings.basic_ad_actions.unused_source_fields]
ads_insights_action_type = [
    "_airbyte_meta",
    "_airbyte_raw_id",
    "account_id",
    "account_name",
    "action_destination",
    "action_target_id",
    "action_attribution_windows",
    "action_carousel_card_id",
    "action_carousel_card_name",
    "action_converted_product_id",
    "action_device",
    "action_event_channel",
    "action_reaction",
    "action_video_sound",
    "action_video_type",
    "ad_name",
    "adset_id",
    "adset_name",
    "campaign_id",
    "campaign_name",
    "inline_link_clicks",
    "objective",
]

[mappings.campaign_history]
source_file = "campaign_history.yml"
source_file_hash = "32ac4c76fbf27a37f854eb283f6172bafbbcc99a1bf6746f98c1e1bafcdfb0ac"
unmapped_target_fields = []
omitted_target_fields = []

[mappings.campaign_history.mapped_target_fields]
id = "campaigns.id"
account_id = "campaigns.account_id"
name = "campaigns.name"
_fivetran_synced = "_airbyte_extracted_at"
updated_time = "campaigns.updated_time"
created_time = "campaigns.created_time"
start_time = "campaigns.start_time"
stop_time = "campaigns.stop_time"
daily_budget = "campaigns.daily_budget"
budget_remaining = "campaigns.budget_remaining"
lifetime_budget = "campaigns.lifetime_budget"
status = "campaigns.status"

[mappings.campaign_history.unused_source_fields]
campaigns = [
    "_airbyte_meta",
    "_airbyte_raw_id",
    "effective_status",
    "objective",
    "special_ad_categories",
    "bid_strategy",
    "issues_info",
    "buying_type",
    "configured_status",
]

[mappings.creative_history]
source_file = "creative_history.yml"
source_file_hash = "21cd62d841a0778db5cec706f4757bdd75edd306b6f66457eb153d729eab3188"
unmapped_target_fields = [
    "_fivetran_id",
    "asset_feed_spec_link_urls",
    "object_story_link_data_caption",
    "object_story_link_data_child_attachments",
    "object_story_link_data_description",
    "object_story_link_data_link",
    "object_story_link_data_message",
    "template_app_link_spec_android",
    "template_app_link_spec_ios",
    "template_app_link_spec_ipad",
    "template_app_link_spec_iphone",
]
omitted_target_fields = []

[mappings.creative_history.mapped_target_fields]
page_link = "ad_creatives.link_url"
template_page_link = "ad_creatives.template_url"
id = "ad_creatives.id"
account_id = "ad_creatives.account_id"
name = "ad_creatives.name"
url_tags = "ad_creatives.url_tags"
_fivetran_synced = "_airbyte_extracted_at"

[mappings.creative_history.unused_source_fields]
ad_creatives = [
    "body",
    "object_story_id",
    "image_url",
    "actor_id",
    "adlabels",
    "applink_treatment",
    "asset_feed_spec",
    "call_to_action_type",
    "effective_instagram_story_id",
    "effective_object_story_id",
    "title",
    "image_crops",
    "instagram_actor_id",
    "instagram_permalink_url",
    "instagram_story_id",
    "link_og_id",
    "object_id",
    "object_story_spec",
    "object_type",
    "object_url",
    "product_set_id",
    "source_instagram_media_id",
    "status",
    "template_url_spec",
    "thumbnail_data_url",
    "thumbnail_url",
    "image_hash",
    "video_id",
    "_airbyte_meta",
    "_airbyte_raw_id",
]
