
-- This file was autogenerated with Airbyte Morph. Please do not modify directly.

WITH
accounts AS (
    SELECT * FROM {{ source('twilio', 'accounts') }}
)


SELECT
    accounts._airbyte_extracted_at AS _fivetran_synced,
    accounts.date_created AS created_at,
    accounts.friendly_name AS friendly_name,
    accounts.sid AS id,
    accounts.owner_account_sid AS owner_account_id,
    accounts.status AS status,
    accounts.type AS type,
    accounts.date_updated AS updated_at
FROM accounts
