
-- This file was autogenerated with Airbyte Morph. Please do not modify directly.

WITH
addresses AS (
    SELECT * FROM {{ source('twilio', 'addresses') }}
)


SELECT
    addresses._airbyte_extracted_at AS _fivetran_synced,
    addresses.account_sid AS account_id,
    addresses.city AS city,
    addresses.date_created AS created_at,
    addresses.customer_name AS customer_name,
    addresses.emergency_enabled AS emergency_enabled,
    addresses.friendly_name AS friendly_name,
    addresses.sid AS id,
    addresses.iso_country AS iso_country,
    addresses.postal_code AS postal_code,
    addresses.region AS region,
    addresses.street AS street,
    addresses.date_updated AS updated_at,
    addresses.validated AS validated,
    addresses.verified AS verified
FROM addresses
