
-- This file was autogenerated with Airbyte Morph. Please do not modify directly.

WITH
incoming_phone_numbers AS (
    SELECT * FROM {{ source('twilio', 'incoming_phone_numbers') }}
)


SELECT
    incoming_phone_numbers._airbyte_extracted_at AS _fivetran_synced,
    incoming_phone_numbers.account_sid AS account_id,
    NULL AS address_id,
    incoming_phone_numbers.address_requirements AS address_requirements,
    incoming_phone_numbers.beta AS beta,
    incoming_phone_numbers.capabilities.mms AS capabilities_mms,
    incoming_phone_numbers.capabilities.sms AS capabilities_sms,
    incoming_phone_numbers.capabilities.voice AS capabilities_voice,
    incoming_phone_numbers.date_created AS created_at,
    incoming_phone_numbers.emergency_address_sid AS emergency_address_id,
    incoming_phone_numbers.emergency_status AS emergency_status,
    incoming_phone_numbers.friendly_name AS friendly_name,
    incoming_phone_numbers.sid AS id,
    incoming_phone_numbers.origin AS origin,
    incoming_phone_numbers.phone_number AS phone_number,
    incoming_phone_numbers.trunk_sid AS trunk_id,
    incoming_phone_numbers.date_updated AS updated_at,
    incoming_phone_numbers.voice_caller_id_lookup AS voice_caller_id_lookup,
    incoming_phone_numbers.voice_url AS voice_url
FROM incoming_phone_numbers
