
-- This file was autogenerated with Airbyte Morph. Please do not modify directly.

WITH
messages AS (
    SELECT * FROM {{ source('twilio', 'messages') }}
)


SELECT
    messages._airbyte_extracted_at AS _fivetran_synced,
    messages.account_sid AS account_id,
    messages.body AS body,
    messages.date_created AS created_at,
    messages.date_sent AS date_sent,
    messages.direction AS direction,
    messages.error_code AS error_code,
    messages.error_message AS error_message,
    messages.from AS from,
    messages.sid AS id,
    messages.messaging_service_sid AS messaging_service_sid,
    messages.num_media AS num_media,
    messages.num_segments AS num_segments,
    messages.price AS price,
    messages.price_unit AS price_unit,
    messages.status AS status,
    messages.to AS to,
    messages.date_updated AS updated_at
FROM messages
