
-- This file was autogenerated with Airbyte Morph. Please do not modify directly.

WITH
outgoing_caller_ids AS (
    SELECT * FROM {{ source('twilio', 'outgoing_caller_ids') }}
)


SELECT
    outgoing_caller_ids._airbyte_extracted_at AS _fivetran_synced,
    outgoing_caller_ids.date_created AS created_at,
    outgoing_caller_ids.friendly_name AS friendly_name,
    outgoing_caller_ids.sid AS id,
    outgoing_caller_ids.phone_number AS phone_number,
    outgoing_caller_ids.date_updated AS updated_at
FROM outgoing_caller_ids
