
-- This file was autogenerated with Airbyte Morph. Please do not modify directly.

WITH
usage_records AS (
    SELECT * FROM {{ source('twilio', 'usage_records') }}
)


SELECT
    usage_records._airbyte_extracted_at AS _fivetran_synced,
    NULL AS account_id,
    usage_records.as_of AS as_of,
    usage_records.category AS category,
    usage_records.count AS count,
    usage_records.count_unit AS count_unit,
    usage_records.description AS description,
    usage_records.end_date AS end_date,
    usage_records.price AS price,
    usage_records.price_unit AS price_unit,
    usage_records.start_date AS start_date,
    usage_records.usage AS usage,
    usage_records.usage_unit AS usage_unit
FROM usage_records
