project_id: shopify.fivetran-interop
source_name: shopify
# Target schema file snapshotted from: https://github.com/fivetran/dbt_shopify_source/blob/main/models/src_shopify.yml
target_dbt_schema_url: https://raw.githubusercontent.com/fivetran/dbt_shopify_source/refs/heads/main/models/src_shopify.yml
# SQL dialect configuration
sql_dialect: duckdb
subcolumn_traversal: dot_notation