name: "airbyte_hubspot"
version: "1.0.0"
config-version: 2

profile: "default"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  airbyte_hubspot:
    +materialized: view

vars:
  airbyte_hubspot_database: "hubspot"
  airbyte_hubspot_schema: "hubspot_raw"
