project_id: quickbooks.airbyte-interop
source_name: quickbooks
# Target schema file snapshotted from: https://github.com/fivetran/dbt_quickbooks_source/blob/main/models/src_quickbooks.yml
target_dbt_schema_url: https://raw.githubusercontent.com/fivetran/dbt_quickbooks_source/refs/heads/main/models/src_quickbooks.yml
# SQL dialect configuration
sql_dialect: duckdb
subcolumn_traversal: dot_notation
