domain: salesforce.airbyte-interop
transforms:
  - name: product_2
    from:
      - MISSING: salesforce.MISSING
    fields:
      id:
        expression: MISSING
        description: The unique, system-generated ID assigned during creation.
      _fivetran_synced:
        expression: MISSING
        description: The time at which fivetran last synced this record
      _fivetran_active:
        expression: MISSING
        description: True if record is active, used to filter out only active records
          if History Mode is enabled
      created_by_id:
        expression: MISSING
        description: Created By ID
      created_date:
        expression: MISSING
        description: Created Date
      description:
        expression: MISSING
        description: A text description of this record. Label is Product Description.
      display_url:
        expression: MISSING
        description: URL leading to a specific version of a record in the linked external
          data source.
      external_data_source_id:
        expression: MISSING
        description: ID of the related external data source.
      external_id:
        expression: MISSING
        description: The unique identifier of a record in the linked external data
          source. For example, ID
      family:
        expression: MISSING
        description: Name of the product family associated with this record. Product
          families are configured as picklists in the user interface. To obtain a
          list of valid values, call describeSObjects() and process the DescribeSObjectResult
          for the values associated with the Family field. Label is Product Family.
      is_active:
        expression: MISSING
        description: Indicates whether this record is active (true) or not (false).
          Inactive Product2 records are hidden in many areas in the user interface.
          You can change the IsActive flag on a Product2 object as often as necessary.
          Label is Active.
      is_archived:
        expression: MISSING
        description: Describes whether the product is archived. The default value
          is false.
      is_deleted:
        expression: MISSING
        description: Indicates whether the object has been moved to the Recycle Bin
          (true) or not (false). Label is Deleted.
      last_modified_by_id:
        expression: MISSING
        description: Last Modified By ID
      last_modified_date:
        expression: MISSING
        description: Last Modified Date
      last_referenced_date:
        expression: MISSING
        description: The timestamp when the current user last accessed this record,
          a record related to this record, or a list view.
      last_viewed_date:
        expression: MISSING
        description: The timestamp when the current user last viewed this record or
          list view. If this value is null, the user might have only accessed this
          record or list view (LastReferencedDate) but not viewed it.
      name:
        expression: MISSING
        description: Required. Default name of this record. Label is Product Name.
      number_of_quantity_installments:
        expression: MISSING
        description: If the product has a quantity schedule, the number of installments.
      number_of_revenue_installments:
        expression: MISSING
        description: If the product has a revenue schedule, the number of installments.
      product_code:
        expression: MISSING
        description: Default product code for this record. Your org defines the product
          code naming pattern.
      quantity_installment_period:
        expression: MISSING
        description: If the product has a quantity schedule, the amount of time covered
          by the schedule.
      quantity_schedule_type:
        expression: MISSING
        description: The type of the quantity schedule, if the product has one.
      quantity_unit_of_measure:
        expression: MISSING
        description: Unit of the product; for example, kilograms, liters, or cases.
          This field comes with only one value, Each, so consider creating your own.
          The QuantityUnitOfMeasure field on ProductItem inherits this field’s values.
      record_type_id:
        expression: MISSING
        description: ID of the record type assigned to this object.
      revenue_installment_period:
        expression: MISSING
        description: If the product has a revenue schedule, the time period covered
          by the schedule.
      revenue_schedule_type:
        expression: MISSING
        description: The type of the revenue schedule, if the product has one.
      stock_keeping_unit:
        expression: MISSING
        description: The SKU for the product. Use in tandem with or instead of the
          ProductCode field. For example, you can track the manufacturer’s identifying
          code in the Product Code field and assign the product a SKU when you resell
          it.
      system_modstamp:
        expression: MISSING
        description: System Modstamp
