Table "order" {
    "_fivetran_synced" varchar [note: '{{ doc(\'_fivetran_synced\') }}']
    "app_id" varchar [note: 'The ID of the app that created the order.']
    "billing_address_address_1" varchar [note: 'The street address of the billing address.']
    "billing_address_address_2" varchar [note: 'An optional additional field for the street address of the billing address.']
    "billing_address_city" varchar [note: 'The city, town, or village of the billing address.']
    "billing_address_company" varchar [note: 'The company of the person associated with the billing address.']
    "billing_address_country" varchar [note: 'The name of the country of the billing address.']
    "billing_address_country_code" varchar [note: 'The two-letter code (ISO 3166-1 format) for the country of the billing address.']
    "billing_address_first_name" varchar [note: 'The first name of the person associated with the payment method.']
    "billing_address_last_name" varchar [note: 'The last name of the person associated with the payment method.']
    "billing_address_latitude" varchar [note: 'The latitude of the billing address.']
    "billing_address_longitude" varchar [note: 'The longitude of the billing address.']
    "billing_address_name" varchar [note: 'The full name of the person associated with the payment method.']
    "billing_address_phone" varchar [note: 'The phone number at the billing address.']
    "billing_address_province" varchar [note: 'The name of the region (province, state, prefecture, …) of the billing address.']
    "billing_address_province_code" varchar [note: 'The two-letter abbreviation of the region of the billing address.']
    "billing_address_zip" varchar [note: 'The postal code (zip, postcode, Eircode, …) of the billing address.']
    "browser_ip" varchar [note: 'The IP address of the browser used by the customer when they placed the order.']
    "buyer_accepts_marketing" varchar [note: 'Whether the customer consented to receive email updates from the shop.']
    "cancel_reason" varchar [note: 'The reason why the order was canceled.']
    "cancelled_at" varchar [note: 'The date and time when the order was canceled.']
    "cart_token" varchar [note: 'The ID of the cart that\'s associated with the order.']
    "closed_at" varchar [note: 'The date and time when the order was closed (archived).']
    "created_at" varchar [note: 'The autogenerated date and time when the order was created in Shopify.']
    "currency" varchar [note: 'The three-letter code for the shop currency.']
    "customer_id" varchar [note: 'The ID of the order\'s customer.']
    "email" varchar [note: 'The customer\'s email address.']
    "financial_status" varchar [note: 'The status of payments associated with the order. Can only be set when the order is created']
    "fulfillment_status" varchar [note: 'The order\'s status in terms of fulfilled line items.']
    "id" varchar [note: 'The ID of the order, used for API purposes. This is different from the order_number property, which is the ID used by the shop owner and customer.']
    "landing_site_base_url" varchar [note: 'The URL for the page where the buyer landed when they entered the shop.']
    "location_id" varchar [note: 'The ID of the physical location where the order was processed.']
    "name" varchar [note: 'The order name, generated by combining the order_number property with the order prefix and suffix that are set in the merchant\'s general settings.']
    "note" varchar [note: 'An optional note that a shop owner can attach to the order.']
    "number" varchar [note: 'The order\'s position in the shop\'s count of orders. Numbers are sequential and start at 1.']
    "order_number" varchar [note: 'The order \'s position in the shop\'s count of orders starting at 1001. Order numbers are sequential and start at 1001.']
    "processed_at" varchar [note: 'The date and time when an order was processed. This value is the date that appears on your orders and that\'s used in the analytic reports.']
    "referring_site" varchar [note: 'The website where the customer clicked a link to the shop.']
    "shipping_address_address_1" varchar [note: 'The street address of the shipping address.']
    "shipping_address_address_2" varchar [note: 'An optional additional field for the street address of the shipping address.']
    "shipping_address_city" varchar [note: 'The city, town, or village of the shipping address.']
    "shipping_address_company" varchar [note: 'The company of the person associated with the shipping address.']
    "shipping_address_country" varchar [note: 'The name of the country of the shipping address.']
    "shipping_address_country_code" varchar [note: 'The two-letter code (ISO 3166-1 format) for the country of the shipping address.']
    "shipping_address_first_name" varchar [note: 'The first name of the person associated with the shipping address.']
    "shipping_address_last_name" varchar [note: 'The last name of the person associated with the shipping address.']
    "shipping_address_latitude" varchar [note: 'The latitude of the shipping address.']
    "shipping_address_longitude" varchar [note: 'The longitude of the shipping address.']
    "shipping_address_name" varchar [note: 'The full name of the person associated with the payment method.']
    "shipping_address_phone" varchar [note: 'The phone number at the shipping address.']
    "shipping_address_province" varchar [note: 'The name of the region (province, state, prefecture, …) of the shipping address.']
    "shipping_address_province_code" varchar [note: 'The two-letter abbreviation of the region of the shipping address.']
    "shipping_address_zip" varchar [note: 'The postal code (zip, postcode, Eircode, …) of the shipping address.']
    "source_name" varchar [note: 'Where the order originated. Can be set only during order creation, and is not writeable afterwards.']
    "subtotal_price" varchar [note: 'The price of the order in the shop currency after discounts but before shipping, taxes, and tips in the shop currency.']
    "taxes_included" varchar [note: 'Whether taxes are included in the order subtotal.']
    "test" varchar [note: 'Whether this is a test order.']
    "token" varchar [note: 'A unique token for the order.']
    "total_discounts" varchar [note: 'The total discounts applied to the price of the order in the shop currency.']
    "total_line_items_price" varchar [note: 'The sum of all line item prices in the shop currency.']
    "total_price" varchar [note: 'The sum of all line item prices, discounts, shipping, taxes, and tips in the shop currency. Must be positive.']
    "total_tax" varchar [note: 'The sum of all the taxes applied to the order in th shop currency. Must be positive.']
    "total_weight" varchar [note: 'The sum of all line item weights in grams.']
    "updated_at" varchar [note: 'The date and time (ISO 8601 format) when the order was last modified.']
    "user_id" varchar [note: 'The ID of the user logged into Shopify POS who processed the order, if applicable.']
    "checkout_token" varchar [note: 'A unique value when referencing the checkout that\'s associated with the order.']
    "confirmed" varchar [note: 'Whether inventory has been reserved for the order.']
    "customer_locale" varchar [note: 'A two-letter or three-letter language code, optionally followed by a region modifier.']
    "checkout_id" varchar [note: 'ID of the order\'s checkout.']
    "order_status_url" varchar [note: 'The URL pointing to the order status web page, if applicable.']
    "_fivetran_deleted" varchar [note: '{{ doc(\'_fivetran_deleted\') }}']
    "total_tip_received" varchar [note: 'The sum of all the tips in the order in the shop currency.']
    "device_id" varchar [note: 'The ID for the device.']
    "presentment_currency" varchar [note: 'The presentment currency that was used to display prices to the customer.']
    "total_shipping_price_set" varchar [note: 'The total shipping price set for the order in presentment and shop currencies.']
    "client_details_user_agent" varchar [note: 'Details of the browsing client, including software and operating versions.']
    "total_tax_set" varchar [note: 'The total tax applied to the order in shop and presentment currencies.']
    "total_shipping_price_set" varchar [note: 'The total shipping price of the order, excluding discounts and returns, in shop and presentment currencies. If taxes_included is set to true, then total_shipping_price_set includes taxes.']
    "total_discounts_set" varchar [note: 'The total discounts applied to the price of the order in shop and presentment currencies.']
    "total_line_items_price_set" varchar [note: 'The total of all line item prices in shop and presentment currencies.']
    "total_price_set" varchar [note: 'The total price of the order in shop and presentment currencies.']
    "is_confirmed" varchar [note: 'Whether the order is confirmed.']
    "source_identifier" varchar [note: 'The ID of the order placed on the originating platform. This value doesn\'t correspond to the Shopify ID that\'s generated from a completed draft.']
}

Table "customer" {
    "_fivetran_synced" varchar [note: '{{ doc(\'_fivetran_synced\') }}']
    "accepts_marketing" varchar [note: 'Whether the customer has consented to receive marketing material via email. Deprecated and will be coalesced with `email_marketing_consent_state`.']
    "created_at" varchar [note: 'The date and time when the customer was created.']
    "default_address_id" varchar [note: 'The default address for the customer.']
    "email" varchar [note: 'The unique email address of the customer. Attempting to assign the same email address to multiple customers returns an error.']
    "first_name" varchar [note: 'The customer\'s first name.']
    "id" varchar [note: 'A unique identifier for the customer.']
    "last_name" varchar [note: 'The customer\'s last name.']
    "orders_count" varchar [note: 'The number of orders associated with this customer.']
    "phone" varchar [note: 'The unique phone number (E.164 format) for this customer. Attempting to assign the same phone number to multiple customers returns an error.']
    "state" varchar [note: 'The state of the customer\'s account with a shop.']
    "tax_exempt" varchar [note: 'Whether the customer is exempt from paying taxes on their order. If true, then taxes won\'t be applied to an order at checkout. If false, then taxes will be applied at checkout.']
    "total_spent" varchar [note: 'The total amount of money that the customer has spent across their order history.']
    "updated_at" varchar [note: 'The date and time when the customer information was last updated.']
    "verified_email" varchar [note: 'Whether the customer has verified their email address.']
    "email_marketing_consent_state" varchar [note: 'The current email marketing state for the customer. New version of `accepts_marketing` field.']
    "email_marketing_consent_opt_in_level" varchar [note: 'The marketing subscription opt-in level, as described in the M3AAWG Sender Best Common Practices, that the customer gave when they consented to receive marketing material by email. New version of `marketing_opt_in_level` field.']
    "email_marketing_consent_consent_updated_at" varchar [note: 'The date and time when the customer consented to receive marketing material by email. If no date is provided, then the date and time when the consent information was sent is used. New version of `accepts_marketing_updated_at` field.']
    "accepts_marketing_updated_at" varchar [note: 'Deprecated. The package will coalesce with `email_marketing_consent_consent_updated_at`.']
    "marketing_opt_in_level" varchar [note: 'Deprecated. The package will coalesce with `email_marketing_consent_opt_in_level`.']
    "_fivetran_deleted" varchar [note: '{{ doc(\'_fivetran_deleted\') }}']
    "note" varchar [note: 'A note about the customer.']
    "currency" varchar [note: 'The three-letter code (ISO 4217 format) for the currency that the customer used when they paid for their last order. Defaults to the shop currency. Returns the shop currency for test orders.']
}

Table "order_line" {
    "_fivetran_synced" varchar [note: '{{ doc(\'_fivetran_synced\') }}']
    "fulfillable_quantity" varchar [note: 'The amount available to fulfill, calculated as follows: quantity - max(refunded_quantity, fulfilled_quantity) - pending_fulfilled_quantity - open_fulfilled_quantity']
    "fulfillment_status" varchar [note: 'How far along an order is in terms line items fulfilled.']
    "gift_card" varchar [note: 'Whether the item is a gift card. If true, then the item is not taxed or considered for shipping charges.']
    "grams" varchar [note: 'The weight of the item in grams.']
    "id" varchar [note: 'The ID of the line item.']
    "name" varchar [note: 'The name of the product variant.']
    "order_id" varchar [note: 'The ID of the related order.']
    "price" varchar [note: 'The price of the item before discounts have been applied in the shop currency.']
    "product_id" varchar [note: 'The ID of the product that the line item belongs to. Can be null if the original product associated with the order is deleted at a later date.']
    "quantity" varchar [note: 'The number of items that were purchased.']
    "requires_shipping" varchar [note: 'Whether the item requires shipping.']
    "sku" varchar [note: 'The item\'s SKU (stock keeping unit).']
    "taxable" varchar [note: 'Whether the item was taxable.']
    "title" varchar [note: 'The title of the product.']
    "total_discount" varchar [note: 'The total amount of the discount allocated to the line item in the shop currency.']
    "variant_id" varchar [note: 'The ID of the product variant.']
    "vendor" varchar [note: 'The name of the item\'s supplier.']
    "index" varchar [note: 'Index of the order line.']
    "pre_tax_price" varchar [note: 'The pre tax price of the line item in shop currency.']
    "pre_tax_price_set" varchar [note: 'The pre tax price of the line item in shop currency and presentment currency.']
    "price_set" varchar [note: 'The price of the line item in shop and presentment currencies.']
    "tax_code" varchar [note: 'Tax code applied to the line item. As multiple taxes can apply to a line item, we recommend referring to `stg_shopify__tax_line`.']
    "total_discount_set" varchar [note: 'The total amount allocated to the line item in the presentment currency.']
    "variant_title" varchar [note: 'The title of the product variant.']
    "variant_inventory_management" varchar [note: 'The fulfillment service that tracks the number of items in stock for the product variant.']
    "properties" varchar [note: 'Line item properties.']
    "tax_code" varchar [note: 'Tax code applied to the line item. As multiple taxes can apply to a line item, we recommend referring to `stg_shopify__tax_line`.']
}

Table "order_line_refund" {
    "_fivetran_synced" varchar [note: '{{ doc(\'_fivetran_synced\') }}']
    "id" varchar [note: 'The unique identifier of the line item in the refund.']
    "location_id" varchar [note: 'TThe unique identifier of the location where the items will be restockedBD']
    "order_line_id" varchar [note: 'The ID of the related line item in the order.']
    "quantity" varchar [note: 'The quantity of the associated line item that was returned.']
    "refund_id" varchar [note: 'The ID of the related refund.']
    "restock_type" varchar [note: 'How this refund line item affects inventory levels.']
    "subtotal" varchar [note: 'Subtotal amount of the order line refund in shop currency.']
    "total_tax" varchar [note: 'The total tax applied to the refund in shop currency.']
    "subtotal_set" varchar [note: 'The subtotal of the refund line item in shop and presentment currencies.']
    "total_tax_set" varchar [note: 'The total tax of the line item in shop and presentment currencies.']
    "subtotal_set" varchar [note: 'The subtotal of the refund line item in shop and presentment currencies.']
}

Table "product" {
    "_fivetran_deleted" varchar [note: 'Whether the record has been deleted in the source system.']
    "_fivetran_synced" varchar [note: '{{ doc(\'_fivetran_synced\') }}']
    "created_at" varchar [note: 'The date and time when the product was created.']
    "handle" varchar [note: 'A unique human-friendly string for the product. Automatically generated from the product\'s title.']
    "id" varchar [note: 'An unsigned 64-bit integer that\'s used as a unique identifier for the product. Each id is unique across the Shopify system. No two products will have the same id, even if they\'re from different shops.']
    "product_type" varchar [note: 'A categorization for the product used for filtering and searching products.']
    "published_at" varchar [note: 'The date and time (ISO 8601 format) when the product was published. Can be set to null to unpublish the product from the Online Store channel.']
    "published_scope" varchar [note: 'Whether the product is published to the Point of Sale channel.']
    "title" varchar [note: 'The name of the product.']
    "updated_at" varchar [note: 'The date and time when the product was last modified.']
    "vendor" varchar [note: 'The name of the product\'s vendor.']
    "status" varchar [note: '''The status of the product. Valid values: - active: The product is ready to sell and is available to customers on the online store, sales channels, and apps. By default, existing products are set to active. - archived: The product is no longer being sold and isn\'t available to customers on sales channels and apps. - draft: The product isn\'t ready to sell and is unavailable to customers on sales channels and apps. By default, duplicated and unarchived products are set to draft.
    ''']
}

Table "product_variant" {
    "barcode" varchar [note: 'The barcode, UPC, or ISBN number for the product.']
    "compare_at_price" varchar [note: 'The original price of the item before an adjustment or a sale in shop currency.']
    "created_at" varchar [note: 'The date and time (ISO 8601 format) when the product variant was created.']
    "fulfillment_service" varchar [note: '(DEPRECATED 2025-01-06) The fulfillment service associated with the product variant.']
    "grams" varchar [note: '(DEPRECATED 2025-01-06) The weight of the product variant in grams.']
    "id" varchar [note: 'The unique numeric identifier for the product variant.']
    "image_id" varchar [note: 'The unique numeric identifier for a product\'s image. The image must be associated to the same product as the variant.']
    "inventory_item_id" varchar [note: 'The unique identifier for the inventory item, which is used in the Inventory API to query for inventory information.']
    "inventory_management" varchar [note: '(DEPRECATED 2025-01-06) The fulfillment service that tracks the number of items in stock for the product variant.']
    "inventory_policy" varchar [note: 'Whether customers are allowed to place an order for the product variant when it\'s out of stock.']
    "inventory_quantity" varchar [note: 'An aggregate of inventory across all locations. To adjust inventory at a specific location, use the InventoryLevel resource.']
    "old_inventory_quantity" varchar [note: '(DEPRECATED 2025-01-06) Use the InventoryLevel resource instead.']
    "option_1" varchar [note: '''(DEPRECATED 2025-01-06) The custom properties that a shop owner uses to define product variants. You can define three options for a product variant: option1, option2, option3.
    ''']
    "option_2" varchar [note: '''(DEPRECATED 2025-01-06) The custom properties that a shop owner uses to define product variants. You can define three options for a product variant: option1, option2, option3.
    ''']
    "option_3" varchar [note: '''(DEPRECATED 2025-01-06) The custom properties that a shop owner uses to define product variants. You can define three options for a product variant: option1, option2, option3.
    ''']
    "position" varchar [note: 'The order of the product variant in the list of product variants. The first position in the list is 1. The position of variants is indicated by the order in which they are listed.']
    "price" varchar [note: 'The price of the product variant in shop currency.']
    "product_id" varchar [note: 'The unique numeric identifier for the product.']
    "requires_shipping" varchar [note: '(DEPRECATED 2025-01-06) Use the `requires_shipping` property on the InventoryItem resource instead.']
    "sku" varchar [note: 'A unique identifier for the product variant in the shop. Required in order to connect to a FulfillmentService.']
    "taxable" varchar [note: 'Whether a tax is charged when the product variant is sold.']
    "tax_code" varchar [note: 'This parameter applies only to the stores that have the Avalara AvaTax app installed. Specifies the Avalara tax code for the product variant.']
    "title" varchar [note: 'The title of the product variant. The title field is a concatenation of the option1, option2, and option3 fields. You can only update title indirectly using the option fields.']
    "updated_at" varchar [note: 'The date and time when the product variant was last modified. Gets returned in ISO 8601 format.']
    "weight" varchar [note: '(DEPRECATED 2025-01-06) The weight of the product variant in the unit system specified with weight_unit.']
    "weight_unit" varchar [note: '''(DEPRECATED 2025-01-06) The unit of measurement that applies to the product variant\'s weight. If you don\'t specify a value for weight_unit, then the shop\'s default unit of measurement is applied. Valid values: g, kg, oz, and lb.
    ''']
    "available_for_sale" varchar [note: 'Indicates whether the product variant is available for sale.']
    "display_name" varchar [note: 'The display name of the variant, based on the product\'s title and variant\'s title.']
    "legacy_resource_id" varchar [note: 'The ID of the corresponding resource in the REST Admin API.']
    "metafield" varchar [note: 'A custom field, including its namespace and key, that\'s associated with a Shopify resource for the purposes of adding and storing additional information.']
    "requires_components" varchar [note: 'Indicates whether a product variant requires components.']
    "sellable_online_quantity" varchar [note: 'The total sellable quantity of the variant for online channels.']
    "_fivetran_synced" varchar [note: '{{ doc(\'_fivetran_synced\') }}']
}

Table "transaction" {
    "id" varchar [note: 'The ID for the transaction.']
    "order_id" varchar [note: 'The ID for the order that the transaction is associated with.']
    "refund_id" varchar [note: 'The ID associated with a refund in the refund table.']
    "amount" varchar [note: 'The amount of money included in the transaction.']
    "authorization" varchar [note: 'The authorization code associated with the transaction.']
    "created_at" varchar [note: 'The date and time when the transaction was created.']
    "processed_at" varchar [note: 'The date and time when a transaction was processed.']
    "device_id" varchar [note: 'The ID for the device.']
    "gateway" varchar [note: 'The name of the gateway the transaction was issued through.']
    "source_name" varchar [note: 'The origin of the transaction.']
    "message" varchar [note: 'A string generated by the payment provider with additional information about why the transaction succeeded or failed.']
    "currency" varchar [note: 'The three-letter code (ISO 4217 format) for the currency used for the payment.']
    "location_id" varchar [note: 'The ID of the physical location where the transaction was processed.']
    "parent_id" varchar [note: 'The ID of an associated transaction.']
    "payment_avs_result_code" varchar [note: 'The response code from the address verification system.']
    "payment_credit_card_bin" varchar [note: 'The issuer identification number (IIN), formerly known as bank identification number (BIN) of the customer\'s credit card.']
    "payment_cvv_result_code" varchar [note: 'The response code from the credit card company indicating whether the customer entered the card security code, or card verification value, correctly.']
    "payment_credit_card_number" varchar [note: 'The customer\'s credit card number, with most of the leading digits redacted.']
    "payment_credit_card_company" varchar [note: 'The name of the company that issued the customer\'s credit card.']
    "kind" varchar [note: 'The transaction\'s type.']
    "receipt" varchar [note: 'A transaction receipt attached to the transaction by the gateway.']
    "currency_exchange_id" varchar [note: 'The ID of the adjustment.']
    "currency_exchange_adjustment" varchar [note: 'The difference between the amounts on the associated transaction and the parent transaction.']
    "currency_exchange_original_amount" varchar [note: 'The amount of the parent transaction in the shop currency.']
    "currency_exchange_final_amount" varchar [note: 'The amount of the associated transaction in the shop currency.']
    "currency_exchange_currency" varchar [note: 'The shop currency.']
    "error_code" varchar [note: 'A standardized error code, independent of the payment provider.']
    "status" varchar [note: 'The status of the transaction.']
    "test" varchar [note: 'Whether the transaction is a test transaction.']
    "user_id" varchar [note: 'The ID for the user who was logged into the Shopify POS device when the order was processed, if applicable.']
    "_fivetran_synced" varchar [note: '{{ doc(\'_fivetran_synced\') }}']
    "authorization_expires_at" varchar [note: 'The date and time (ISO 8601 format) when the Shopify Payments authorization expires.']
}

Table "refund" {
    "id" varchar [note: 'The unique numeric identifier for the refund.']
    "created_at" varchar [note: 'Timestamp of the date when the refund was created.']
    "processed_at" varchar [note: 'Timestamp of the date when the refund was processed.']
    "note" varchar [note: 'User generated note attached to the refund.']
    "restock" varchar [note: 'Boolean indicating if the refund is a result of a restock.']
    "user_id" varchar [note: 'Reference to the user id which generated the refund.']
    "_fivetran_synced" varchar [note: '{{ doc(\'_fivetran_synced\') }}']
    "total_duties_set" varchar [note: 'Record representing total duties set for the refund.']
    "order_id" varchar [note: 'Reference to the order which the refund is associated.']
}

Table "order_adjustment" {
    "id" varchar [note: 'The unique numeric identifier for the order adjustment.']
    "order_id" varchar [note: 'Reference to the order which the adjustment is associated.']
    "refund_id" varchar [note: 'Reference to the refund which the adjustment is associated.']
    "amount" varchar [note: 'Amount of the adjustment.']
    "tax_amount" varchar [note: 'Tax amount applied to the order adjustment in shop currency.']
    "kind" varchar [note: 'The kind of order adjustment (eg. refund, restock, etc.).']
    "reason" varchar [note: 'The reason for the order adjustment.']
    "amount_set" varchar [note: 'Amount set towards the order adjustment in shop and presentment currencies.']
    "tax_amount_set" varchar [note: 'Tax amount set towards the order adjustment in shop and presentment currencies.']
    "_fivetran_synced" varchar [note: '{{ doc(\'_fivetran_synced\') }}']
}

Table "abandoned_checkout" {
    "_fivetran_deleted" varchar [note: '{{ doc(\'_fivetran_deleted\') }}']
    "_fivetran_synced" varchar [note: '{{ doc(\'_fivetran_synced\') }}']
    "abandoned_checkout_url" varchar [note: 'The recovery URL that\'s sent to a customer so they can recover their checkout.']
    "billing_address_address_1" varchar [note: 'The street address of the billing address.']
    "billing_address_address_2" varchar [note: 'An optional additional field for the street address of the billing address.']
    "billing_address_city" varchar [note: 'The city of the billing address.']
    "billing_address_company" varchar [note: 'The company of the person associated with the billing address.']
    "billing_address_country" varchar [note: 'The name of the country of the billing address.']
    "billing_address_country_code" varchar [note: 'The two-letter code (ISO 3166-1 alpha-2 format) for the country of the billing address.']
    "billing_address_first_name" varchar [note: 'The first name of the person associated with the payment method.']
    "billing_address_last_name" varchar [note: 'The last name of the person associated with the payment method.']
    "billing_address_latitude" varchar [note: 'The latitude of the billing address.']
    "billing_address_longitude" varchar [note: 'The longitude of the billing address.']
    "billing_address_name" varchar [note: 'The full name of the person associated with the payment method.']
    "billing_address_phone" varchar [note: 'The phone number at the billing address.']
    "billing_address_province" varchar [note: 'The name of the state or province of the billing address.']
    "billing_address_province_code" varchar [note: 'The two-letter abbreviation of the state or province of the billing address.']
    "billing_address_zip" varchar [note: 'The zip or postal code of the billing address.']
    "buyer_accepts_marketing" varchar [note: 'Whether the customer would like to receive email updates from the shop. This is set by the \'I want to receive occasional emails about new products, promotions and other news\' checkbox during checkout.']
    "cart_token" varchar [note: 'The ID for the cart that\'s attached to the checkout.']
    "closed_at" varchar [note: 'The date and time (ISO 8601 format) when the checkout was closed. If the checkout was not closed, then this value is null.']
    "created_at" varchar [note: 'The date and time (ISO 8601 format) when the checkout was created.']
    "currency" varchar [note: 'The three-letter code (ISO 4217 format) of the shop\'s default currency at the time of checkout. For the currency that the customer used at checkout, see `presentment_currency`.']
    "customer_id" varchar [note: 'ID of the customer with the abandoned checkout.']
    "customer_locale" varchar [note: 'The two or three-letter language code, optionally followed by a region modifier. Example values - en, en-CA.']
    "device_id" varchar [note: 'The ID of the Shopify POS device that created the checkout.']
    "email" varchar [note: 'The customer\'s email address.']
    "gateway" varchar [note: 'The payment gateway used by the checkout.']
    "id" varchar [note: 'The ID for the checkout.']
    "landing_site_base_url" varchar [note: 'The URL for the page where the customer entered the shop.']
    "location_id" varchar [note: 'The ID of the physical location where the checkout was processed.']
    "name" varchar [note: 'Checkout order number.']
    "note" varchar [note: 'The text of an optional note that a shop owner can attach to the order.']
    "phone" varchar [note: 'The customer\'s phone number for receiving SMS notifications.']
    "presentment_currency" varchar [note: 'The three-letter code (ISO 4217 format) of the currency that the customer used at checkout. For the shop\'s default currency, see `currency`.']
    "referring_site" varchar [note: 'The website that referred the customer to the shop.']
    "shipping_address_address_1" varchar [note: 'The street address of the shipping address.']
    "shipping_address_address_2" varchar [note: 'An optional additional field for the street address of the shipping address.']
    "shipping_address_city" varchar [note: 'The city of the shipping address.']
    "shipping_address_company" varchar [note: 'The company of the person associated with the shipping address.']
    "shipping_address_country" varchar [note: 'The name of the country of the shipping address.']
    "shipping_address_country_code" varchar [note: 'The two-letter code (ISO 3166-1 alpha-2 format) for the country of the shipping address.']
    "shipping_address_first_name" varchar [note: 'The first name of the person associated with the shipping address.']
    "shipping_address_last_name" varchar [note: 'The last name of the person associated with the shipping address.']
    "shipping_address_latitude" varchar [note: 'The latitude of the shipping address.']
    "shipping_address_longitude" varchar [note: 'The longitude of the shipping address.']
    "shipping_address_name" varchar [note: 'The full name of the person associated with the shipping address.']
    "shipping_address_phone" varchar [note: 'The phone number at the shipping address.']
    "shipping_address_province" varchar [note: 'The name of the state or province of the shipping address.']
    "shipping_address_province_code" varchar [note: 'The two-letter abbreviation of the state or province of the shipping address.']
    "shipping_address_zip" varchar [note: 'The zip or postal code of the shipping address.']
    "source_name" varchar [note: 'Where the checkout originated. Valid values include `web`, `pos`, `iphone`, `android`.']
    "subtotal_price" varchar [note: 'The price of the checkout in _presentment_ (customer) currency before shipping and taxes.']
    "taxes_included" varchar [note: 'Boolean representing whether taxes are included in the price.']
    "token" varchar [note: 'A unique ID for a checkout.']
    "total_discounts" varchar [note: 'The total amount of discounts to be applied in presentment currency.']
    "total_duties" varchar [note: 'The total duties of the checkout in presentment currency.']
    "total_line_items_price" varchar [note: 'The sum of the prices of all line items in the checkout in _presentment_ (customer) currency.']
    "total_price" varchar [note: 'The sum of line item prices, all discounts, shipping costs, and taxes for the checkout in _presentment_ (customer) currency.']
    "total_tax" varchar [note: 'The sum of all the taxes applied to the checkout in _presentment_ (customer) currency.']
    "total_weight" varchar [note: 'The sum of all the weights in grams of the line items in the checkout.']
    "updated_at" varchar [note: 'The date and time (ISO 8601 format) when the checkout was last modified.']
    "user_id" varchar [note: 'The ID of the user who created the checkout.']
}

Table "collection_product" {
    "_fivetran_synced" varchar [note: '{{ doc(\'_fivetran_synced\') }}']
    "collection_id" varchar [note: 'ID referencing the `collection` the product belongs to.']
    "product_id" varchar [note: 'ID referencing the `product`.']
}

Table "collection" {
    "_fivetran_deleted" varchar [note: '{{ doc(\'_fivetran_deleted\') }}']
    "_fivetran_synced" varchar [note: '{{ doc(\'_fivetran_synced\') }}']
    "disjunctive" varchar [note: 'Boolean representing whether the `rules` or disjuctive (logical `OR`) or not. True = disjuctive, false = conjunctive (logical `AND`).']
    "handle" varchar [note: 'A unique, human-readable string for the collection automatically generated from its title. This is used in themes by the Liquid templating language to refer to the collection.']
    "id" varchar [note: 'The ID for the collection.']
    "published_at" varchar [note: 'The time and date (ISO 8601 format) when the collection was made visible. Returns null for a hidden collection.']
    "published_scope" varchar [note: '''Whether the collection is published to the Point of Sale channel. Valid values `web` (the collection is published to the Online Store channel but not published to the Point of Sale channel) and `global` (the collection is published to both the Online Store channel and the Point of Sale channel).
    ''']
    "rules" varchar [note: '''An array of rules that define what products go into the smart collection. Each rule (`column` -- `relation` --> `condition`) has these properties: - `column`: the property of a product being used to populate the smart collection. Ex: \'tag\', \'type\', \'vendor\', \'variant_price\', etc. - `relation`: The comparitive relationship between the column choice, and the condition (\'equals\', \'contains\', \'greater_than\', etc.) - condition: Select products for a smart collection using a condition. Values are either strings or numbers, depending on the relation value. See the [Shopify docs](https://shopify.dev/api/admin-rest/2022-10/resources/smartcollection#resource-object) for more.
    ''']
    "sort_order" varchar [note: '''The order of the products in the collection. Valid values inclide - `alpha-asc`: The products are sorted alphabetically from A to Z. - `alpha-des`: The products are sorted alphabetically from Z to A. - `best-selling`: The products are sorted by number of sales. - `created`: The products are sorted by the date they were created, from oldest to newest. - `created-desc`: The products are sorted by the date they were created, from newest to oldest. - `manual`: The products are manually sorted by the shop owner. - `price-asc`: The products are sorted by price from lowest to highest. - `price-desc`: The products are sorted by price from highest to lowest.
    ''']
    "title" varchar [note: 'The name of the collection']
    "updated_at" varchar [note: 'The date and time (ISO 8601 format) when the collection was last modified.']
}

Table "customer_tag" {
    "_fivetran_synced" varchar [note: '{{ doc(\'_fivetran_synced\') }}']
    "index" varchar [note: 'Index (starting from 1) represnting when the tag was placed on the customer.']
    "customer_id" varchar [note: 'ID of the customer being tagged.']
    "value" varchar [note: 'Value of the tag.']
}

Table "discount_code" {
    "_fivetran_synced" varchar [note: '{{ doc(\'_fivetran_synced\') }}']
    "code" varchar [note: 'The case-insensitive discount code that customers use at checkout. Shopify recommends this map onto the associated `price_rule.title`.']
    "created_at" varchar [note: 'The date and time (ISO 8601 format) when the discount code was created.']
    "id" varchar [note: 'The ID for the discount code.']
    "price_rule_id" varchar [note: 'The ID for the price rule that this discount code belongs to.']
    "updated_at" varchar [note: 'The date and time (ISO 8601 format) when the discount code was updated.']
    "usage_count" varchar [note: 'The number of times that the discount code has been redeemed.']
}

Table "fulfillment" {
    "_fivetran_synced" varchar [note: '{{ doc(\'_fivetran_synced\') }}']
    "created_at" varchar [note: 'The date and time when the fulfillment was created. The API returns this value in ISO 8601 format.']
    "id" varchar [note: 'The ID for the fulfillment.']
    "location_id" varchar [note: 'The unique identifier of the location that the fulfillment was processed at.']
    "name" varchar [note: '''The uniquely identifying fulfillment name, consisting of two parts separated by a .. The first part represents the order name and the second part represents the fulfillment number.  The fulfillment number automatically increments depending on how many fulfillments are in an order (e.g. #1001.1, #1001.2).
    ''']
    "order_id" varchar [note: 'The unique numeric identifier for the order.']
    "receipt_authorization" varchar [note: 'The authorization code from the receipt.']
    "service" varchar [note: 'The fulfillment service associated with the fulfillment.']
    "shipment_status" varchar [note: '''The current shipment status of the fulfillment. Valid values include: - label_printed: A label for the shipment was purchased and printed. - label_purchased: A label for the shipment was purchased, but not printed. - attempted_delivery: Delivery of the shipment was attempted, but unable to be completed. - ready_for_pickup: The shipment is ready for pickup at a shipping depot. - confirmed: The carrier is aware of the shipment, but hasn\'t received it yet. - in_transit: The shipment is being transported between shipping facilities on the way to its destination. - out_for_delivery: The shipment is being delivered to its final destination. - delivered: The shipment was succesfully delivered. - failure: Something went wrong when pulling tracking information for the shipment, such as the tracking number was invalid or the shipment was canceled.
    ''']
    "status" varchar [note: '''The status of the fulfillment. Valid values include: - pending: Shopify has created the fulfillment and is waiting for the third-party fulfillment service to transition it to \'open\' or \'success\'. - open: The fulfillment has been acknowledged by the service and is in processing. - success: The fulfillment was successful. - cancelled: The fulfillment was cancelled. - error: There was an error with the fulfillment request. - failure: The fulfillment request failed.
    ''']
    "tracking_company" varchar [note: 'The name of the tracking company.']
    "tracking_number" varchar [note: 'Primary tracking number for the order.']
    "tracking_numbers" varchar [note: 'A list of tracking numbers, provided by the shipping company.']
    "tracking_urls" varchar [note: 'The URLs of tracking pages for the fulfillment.']
    "updated_at" varchar [note: 'The date and time (ISO 8601 format) when the fulfillment was last modified.']
}

Table "inventory_item" {
    "_fivetran_deleted" varchar [note: '{{ doc(\'_fivetran_deleted\') }}']
    "_fivetran_synced" varchar [note: '{{ doc(\'_fivetran_synced\') }}']
    "country_code_of_origin" varchar [note: 'The country code (ISO 3166-1 alpha-2) of where the item came from.']
    "created_at" varchar [note: 'The date and time (ISO 8601 format) when the inventory item was created.']
    "id" varchar [note: 'The ID of the inventory item.']
    "province_code_of_origin" varchar [note: 'The province code (ISO 3166-2 alpha-2) of where the item came from. The province code is only used if the shipping provider for the inventory item is Canada Post.']
    "requires_shipping" varchar [note: 'Boolean representing whether a customer needs to provide a shipping address when placing an order containing the inventory item.']
    "sku" varchar [note: 'The unique SKU (stock keeping unit) of the inventory item.']
    "tracked" varchar [note: 'Boolean representing whether inventory levels are tracked for the item. If true, then the inventory quantity changes are tracked by Shopify.']
    "updated_at" varchar [note: 'The date and time (ISO 8601 format) when the inventory item was last modified.']
    "duplicate_sku_count" varchar [note: 'The number of inventory items that share the same SKU with this item.']
    "harmonized_system_code" varchar [note: 'The harmonized system code of the item.']
    "inventory_history_url" varchar [note: 'The URL that points to the inventory history for the item.']
    "legacy_resource_id" varchar [note: 'The ID of the corresponding resource in the REST Admin API.']
    "measurement_id" varchar [note: 'The unique identifier for the inventory item\'s measurement.']
    "measurement_weight_value" varchar [note: 'The weight value of the inventory item\'s measurement.']
    "measurement_weight_unit" varchar [note: 'The unit of measurement for the inventory item\'s weight.']
    "tracked_editable_locked" varchar [note: 'Indicates whether the \'tracked\' field for the inventory item is locked from editing.']
    "tracked_editable_reason" varchar [note: 'Provides the reason why the \'tracked\' field for the inventory item is locked from editing.']
    "unit_cost_amount" varchar [note: 'Decimal money amount of the unit cost associated with the inventory item.']
    "unit_cost_currency_code" varchar [note: 'Currency of the unit cost associated with the inventory item.']
}

Table "inventory_level" {
    "_fivetran_synced" varchar [note: '{{ doc(\'_fivetran_synced\') }}']
    "available" varchar [note: '(DEPRECATED 2025-01-06) The available quantity of an inventory item at the inventory level\'s associated location. Returns null if the inventory item is not tracked.']
    "inventory_item_id" varchar [note: 'The ID of the inventory item associated with the inventory level.']
    "location_id" varchar [note: 'The ID of the location that the inventory level belongs to.']
    "updated_at" varchar [note: 'The date and time (ISO 8601 format) when the inventory level was last modified.']
    "id" varchar [note: 'A globally unique identifier for the inventory level.']
    "can_deactivate" varchar [note: 'Indicates whether the inventory item can be deactivated at the location.']
    "created_at" varchar [note: 'The date and time when the inventory level was created.']
    "deactivation_alert" varchar [note: 'Provides an alert message when the inventory item is deactivated at the location.']
}

Table "inventory_quantity" {
    "id" varchar [note: 'The unique identifier for the record.']
    "inventory_item_id" varchar [note: 'The ID of the inventory item associated with this record.']
    "inventory_level_id" varchar [note: 'The ID of the inventory level where this item is stored.']
    "name" varchar [note: 'The name of the inventory state associated with the record. [Link to list of expected values](https://shopify.dev/docs/apps/build/orders-fulfillment/inventory-management-apps#inventory-states).']
    "quantity" varchar [note: 'The available quantity of the inventory item.']
    "updated_at" varchar [note: 'The timestamp of the last update to the inventory record.']
    "_fivetran_synced" varchar [note: '{{ doc(\'_fivetran_synced\') }}']
}

Table "location" {
    "_fivetran_deleted" varchar [note: '{{ doc(\'_fivetran_deleted\') }}']
    "_fivetran_synced" varchar [note: '{{ doc(\'_fivetran_synced\') }}']
    "active" varchar [note: '''Boolean representing whether the location is active. If true, then the location can be used to sell products, stock inventory, and fulfill orders.
    ''']
    "address_1" varchar [note: 'The location\'s street address.']
    "address_2" varchar [note: 'The optional second line of the location\'s street address.']
    "city" varchar [note: 'The city the location is in.']
    "country" varchar [note: 'The country the location is in (two-letter code).']
    "country_code" varchar [note: 'The two-letter code (ISO 3166-1 alpha-2 format) corresponding to country the location is in.']
    "country_name" varchar [note: 'Full name of the location\'s country.']
    "created_at" varchar [note: 'The date and time (ISO 8601 format) when the location was created.']
    "id" varchar [note: 'The ID of the location.']
    "legacy" varchar [note: '''Boolean representing whether this is a fulfillment service location. If true, then the location is a fulfillment service location.  If false, then the location was created by the merchant and isn\'t tied to a fulfillment service.
    ''']
    "localized_country_name" varchar [note: 'The localized name of the location\'s country.']
    "localized_province_name" varchar [note: 'The localized name of the location\'s region. Typically a province, state, or district.']
    "name" varchar [note: 'The name of the location.']
    "phone" varchar [note: 'The phone number of the location. This value can contain special characters, such as - or +.']
    "province" varchar [note: 'The province, state, or district of the location.']
    "province_code" varchar [note: 'The province, state, or district code (ISO 3166-2 alpha-2 format) of the location.']
    "updated_at" varchar [note: 'The date and time (ISO 8601 format) when the location was last updated.']
    "zip" varchar [note: 'The zip or postal code.']
}

Table "metafield" {
    "_fivetran_synced" varchar [note: '{{ doc(\'_fivetran_synced\') }}']
    "created_at" varchar [note: 'The date and time (ISO 8601 format) when the metafield was created.']
    "description" varchar [note: 'A description of the information that the metafield contains.']
    "id" varchar [note: 'The unique ID of the metafield.']
    "key" varchar [note: 'The key of the metafield. Keys can be up to 64 characters long and can contain alphanumeric characters, hyphens, underscores, and periods.']
    "namespace" varchar [note: 'A container for a group of metafields. Grouping metafields within a namespace prevents your metafields from conflicting with other metafields with the same key name. Must have between 3-255 characters.']
    "owner_id" varchar [note: 'The unique ID of the resource that the metafield is attached to.']
    "owner_resource" varchar [note: 'The type of resource (table) that the metafield is attached to.']
    "type" varchar [note: 'The type of data that the metafield stores in the `value` field. Refer to the [list](https://shopify.dev/apps/metafields/types) of supported types. Use this instead of `value_type`.']
    "updated_at" varchar [note: 'The date and time (ISO 8601 format) when the metafield was last updated.']
    "value" varchar [note: 'The data to store in the metafield. The value is always stored as a string, regardless of the metafield\'s type.']
    "value_type" varchar [note: 'DEPRECATED as of [June 2022](https://fivetran.com/docs/applications/shopify/changelog#june2022). Use `type` instead.']
}

Table "order_note_attribute" {
    "_fivetran_synced" varchar [note: '{{ doc(\'_fivetran_synced\') }}']
    "name" varchar [note: 'Name of the attribute.']
    "order_id" varchar [note: 'ID referencing the order the note attribute belongs to.']
    "value" varchar [note: 'Value of the attribute.']
}

Table "order_shipping_line" {
    "_fivetran_synced" varchar [note: '{{ doc(\'_fivetran_synced\') }}']
    "carrier_identifier" varchar [note: 'A reference to the carrier service that provided the rate. Present when the rate was computed by a third-party carrier service.']
    "code" varchar [note: 'A reference to the shipping method.']
    "delivery_category" varchar [note: 'The general classification of the delivery method.']
    "discounted_price" varchar [note: 'The pre-tax shipping price with discounts applied in the shop currency.']
    "discounted_price_set" varchar [note: 'The pre-tax shipping price with discounts applied (JSON) in presentment and shop currencies.']
    "id" varchar [note: 'A globally-unique identifier.']
    "order_id" varchar [note: 'ID of the associated order.']
    "phone" varchar [note: 'The phone number at the shipping address.']
    "price" varchar [note: 'Returns the price of the shipping line in shop currency.']
    "price_set" varchar [note: 'Returns the price of the shipping line (JSON) in presentment and shop currencies.']
    "requested_fulfillment_service_id" varchar [note: 'The fulfillment service requested for the shipping method. Present if the shipping method requires processing by a third party fulfillment service.']
    "source" varchar [note: 'Returns the rate source for the shipping line.']
    "title" varchar [note: 'Returns the title of the shipping line.']
}

Table "order_shipping_tax_line" {
    "_fivetran_synced" varchar [note: '{{ doc(\'_fivetran_synced\') }}']
    "index" varchar [note: 'Index (from 1) representing the order of shipping lines per order.']
    "order_shipping_line_id" varchar [note: 'ID of the order shipping line this recod is associated with.']
    "price" varchar [note: 'The amount of tax, in shop currency, after discounts and before returns.']
    "price_set" varchar [note: 'The amount of tax, in shop and presentment currencies, after discounts and before returns (JSON).']
    "rate" varchar [note: 'The proportion of the line item price that the tax represents as a decimal.']
    "title" varchar [note: 'The name of the tax.']
}

Table "order_tag" {
    "_fivetran_synced" varchar [note: '{{ doc(\'_fivetran_synced\') }}']
    "index" varchar [note: 'Index (starting from 1) represnting when the tag was placed on the order.']
    "order_id" varchar [note: 'ID of the order being tagged.']
    "value" varchar [note: 'Value of the tag.']
}

Table "order_url_tag" {
    "_fivetran_synced" varchar [note: '{{ doc(\'_fivetran_synced\') }}']
    "key" varchar [note: 'Key of the tag pair.']
    "order_id" varchar [note: 'ID of the order url being tagged.']
    "value" varchar [note: 'Value of the tag.']
}

Table "price_rule" {
    "_fivetran_synced" varchar [note: '{{ doc(\'_fivetran_synced\') }}']
    "allocation_limit" varchar [note: '''The number of times the discount can be allocated on the cart - if eligible. For example a Buy 1 hat Get 1 hat for free discount can be applied 3 times on a cart having more than 6 hats,  where maximum of 3 hats get discounted - if the allocation_limit is 3. Empty (null) allocation_limit means unlimited number of allocations.
    ''']
    "allocation_method" varchar [note: '''The allocation method of the price rule. Valid values include `each` (the discount is applied to each of the entitled items. For example, for a price rule that takes $15 off, each entitled line item in a checkout will be discounted by $15) and `across` (the calculated discount amount will be applied across the entitled items. For example, for a price rule that takes $15 off, the discount will be applied across all the entitled items).
    ''']
    "created_at" varchar [note: 'The date and time (ISO 8601 format) when the price rule was created.']
    "customer_selection" varchar [note: '''The customer selection for the price rule. Valid values include `all` (the price rule is valid for all customers) and `prerequisite`  (the customer must either belong to one of the customer segments specified by customer_segment_prerequisite_ids, or be one of the customers specified by prerequisite_customer_ids).
    ''']
    "ends_at" varchar [note: 'The date and time (ISO 8601 format) when the price rule ends. Must be after starts_at.']
    "id" varchar [note: 'The ID for the price rule.']
    "once_per_customer" varchar [note: 'Boolean representing whether the generated discount code will be valid only for a single use per customer. This is tracked using customer ID.']
    "prerequisite_quantity_range" varchar [note: 'If `customer_selection` is `prerequisite`, the minimum number of items for the price rule to be applicable. The quantity of an entitled cart item must be greater than or equal to this value.']
    "prerequisite_shipping_price_range" varchar [note: 'If `customer_selection` is `prerequisite`, the maximum shipping price for the price rule to be applicable. The shipping price must be less than or equal to this value']
    "prerequisite_subtotal_range" varchar [note: 'If `customer_selection` is `prerequisite`, the minimum subtotal for the price rule to be applicable. The subtotal of the entitled cart items must be greater than or equal to this value for the discount to apply.']
    "prerequisite_to_entitlement_purchase_prerequisite_amount" varchar [note: 'If `customer_selection` is `prerequisite`, the prerequisite purchase for a Buy X Get Y discount. The minimum purchase amount required to be entitled to the discount.']
    "quantity_ratio_entitled_quantity" varchar [note: 'If `customer_selection` is `prerequisite`, in a Buy/Get ratio for a Buy X Get Y discount, this is the offered \'get\' quantity.']
    "quantity_ratio_prerequisite_quantity" varchar [note: 'If `customer_selection` is `prerequisite`, in a Buy/Get ratio for a Buy X Get Y discount, this defines the necessary \'buy\' quantity.']
    "starts_at" varchar [note: 'The date and time (ISO 8601 format) when the price rule starts.']
    "target_selection" varchar [note: '''The target selection method of the price rule. Valid values include `all` (the price rule applies the discount to all line items in the checkout) and  `entitled` (the price rule applies the discount to selected entitlements only).
    ''']
    "target_type" varchar [note: 'The target type that the price rule applies to. Valid values include `line_item` (the price rule applies to the cart\'s line items) and `shipping_line` (the price rule applies to the cart\'s shipping lines).']
    "title" varchar [note: '''The title of the price rule. This is used by the Shopify admin search to retrieve discounts. It is also displayed on the Discounts page of the Shopify admin for bulk discounts.  Shopify recommends that this map onto the associated `discount_code.code`.
    ''']
    "updated_at" varchar [note: 'The date and time (ISO 8601 format) when the price rule was updated.']
    "usage_limit" varchar [note: 'The maximum number of times the price rule can be used, per discount code.']
    "value" varchar [note: 'The value of the price rule. If if the value of `target_type` is `shipping_line`, then only -100 is accepted. The value must be negative.']
    "value_type" varchar [note: '''The value type of the price rule. Valid values include `fixed_amount` (applies a discount of value as a unit of the store\'s currency. For example, if value is -30 and the store\'s currency is USD, then $30 USD is deducted when the discount is applied) and `percentage` (applies a percentage discount of value. For example, if value is -30, then 30% will be deducted when the discount is applied).
    If `target_type` is `shipping_line`, then only `percentage` is accepted.
    ''']
}

Table "product_image" {
    "_fivetran_deleted" varchar [note: '{{ doc(\'_fivetran_deleted\') }}']
    "_fivetran_synced" varchar [note: '{{ doc(\'_fivetran_synced\') }}']
    "created_at" varchar [note: '(DEPRECATED 2025-01-06) The date and time when the product image was created. The API returns this value in ISO 8601 format.']
    "height" varchar [note: 'Height dimension of the image which is determined on upload.']
    "id" varchar [note: 'Unique numeric identifier of the product image.']
    "position" varchar [note: '(DEPRECATED 2025-01-06) The order of the product image in the list. The first product image is at position 1 and is the "main" image for the product.']
    "product_id" varchar [note: 'The id of the product associated with the image.']
    "src" varchar [note: '(DEPRECATED 2025-01-06) Specifies the location of the product image. This parameter supports URL filters that you can use to retrieve modified copies of the image.']
    "updated_at" varchar [note: '(DEPRECATED 2025-01-06) The date and time when the product image was last modified. The API returns this value in ISO 8601 format.']
    "variant_ids" varchar [note: '(DEPRECATED 2025-01-06) An array of variant ids associated with the image.']
    "width" varchar [note: 'Width dimension of the image which is determined on upload.']
    "alt_text" varchar [note: 'A word or phrase to share the nature or contents of an image.']
    "media_id" varchar [note: 'The unique identifier for the media associated with the product image.']
    "status" varchar [note: 'The status of the product image, indicating its availability or processing state.']
    "url" varchar [note: 'The URL of the product image.']
}

Table "product_tag" {
    "_fivetran_synced" varchar [note: '{{ doc(\'_fivetran_synced\') }}']
    "index" varchar [note: 'Index (starting from 1) represnting when the tag was placed on the product.']
    "product_id" varchar [note: 'ID of the product being tagged.']
    "value" varchar [note: 'Value of the tag.']
}

Table "shop" {
    "_fivetran_deleted" varchar [note: '{{ doc(\'_fivetran_deleted\') }}']
    "_fivetran_synced" varchar [note: '{{ doc(\'_fivetran_synced\') }}']
    "address_1" varchar [note: 'The shop\'s street address.']
    "address_2" varchar [note: 'The optional second line of the shop\'s street address.']
    "checkout_api_supported" varchar [note: 'Boolean representing whether the shop is capable of accepting payments directly through the Checkout API.']
    "city" varchar [note: 'The shop\'s city.']
    "cookie_consent_level" varchar [note: 'The cookie consent level defined on the shop\'s online store.']
    "country" varchar [note: 'The shop\'s country. In most cases, this value matches the country_code.']
    "country_code" varchar [note: 'The two-letter country code corresponding to the shop\'s country.']
    "country_name" varchar [note: 'The shop\'s normalized country name.']
    "county_taxes" varchar [note: 'Boolean representing whether the shop is applying taxes on a per-county basis. Only applicable to shops based in the US. Either `true` or `null` (not false, according to Shopify API docs).']
    "created_at" varchar [note: 'The date and time (ISO 8601) when the shop was created.']
    "currency" varchar [note: 'The three-letter code (ISO 4217 format) for the shop\'s default currency.']
    "customer_email" varchar [note: 'The contact email used for communication between the shop owner and the customer.']
    "domain" varchar [note: 'The shop\'s domain.']
    "eligible_for_card_reader_giveaway" varchar [note: 'Boolean representing whether the shop is eligible to receive a free credit card reader from Shopify.']
    "eligible_for_payments" varchar [note: 'Boolean representing whether the shop is eligible to use Shopify Payments.']
    "email" varchar [note: 'The contact email used for communication between Shopify and the shop owner.']
    "enabled_presentment_currencies" varchar [note: 'An array of of enabled currencies (ISO 4217 format) that the shop accepts. Merchants can enable currencies from their Shopify Payments settings in the Shopify Admin.']
    "force_ssl" varchar [note: 'DEPRECATED.']
    "google_apps_domain" varchar [note: 'The GSuite URL for the store, if applicable.']
    "google_apps_login_enabled" varchar [note: 'Boolean representing whether the GSuite login is enabled. Shops with this feature will be able to log in through the GSuite login page. Valid values are `true` and `null`.']
    "has_discounts" varchar [note: 'Boolean representing whether any active discounts exist for the shop.']
    "has_gift_cards" varchar [note: 'Boolean representing whether any active gift cards exist for the shop.']
    "has_storefront" varchar [note: 'Boolean representing whether this shop has an online store.']
    "iana_timezone" varchar [note: 'The name of the timezone assigned by the [IANA](https://www.iana.org/time-zones).']
    "id" varchar [note: 'The ID for the shop. A 64-bit unsigned integer.']
    "latitude" varchar [note: 'The latitude of the shop\'s location.']
    "longitude" varchar [note: 'The longitude of the shop\'s location.']
    "money_format" varchar [note: 'A string representing the way currency is formatted when the currency isn\'t specified.']
    "money_in_emails_format" varchar [note: 'A string representing the way currency is formatted in email notifications when the currency isn\'t specified.']
    "money_with_currency_format" varchar [note: 'A string representing the way currency is formatted when the currency is specified.']
    "money_with_currency_in_emails_format" varchar [note: 'A string representing the way currency is formatted in email notifications when the currency is specified.']
    "multi_location_enabled" varchar [note: 'DEPRECATED and hard-coded to `true`.']
    "myshopify_domain" varchar [note: 'The shop\'s .myshopify.com domain.']
    "name" varchar [note: 'The name of the shop.']
    "password_enabled" varchar [note: 'Boolean representing whether the password protection page is enabled on the shop\'s online store.']
    "phone" varchar [note: 'The contact phone number for the shop.']
    "plan_display_name" varchar [note: 'The display name of the Shopify plan the shop is on.']
    "plan_name" varchar [note: 'The name of the Shopify plan the shop is on.']
    "pre_launch_enabled" varchar [note: 'Boolen representing whether the pre-launch page is enabled on the shop\'s online store.']
    "primary_locale" varchar [note: 'The shop\'s primary locale, as configured in the language settings of the shop\'s theme.']
    "primary_location_id" varchar [note: 'DEPRECATED. Formerly used for the ID of the shipping origin location.']
    "province" varchar [note: 'The shop\'s normalized province or state name.']
    "province_code" varchar [note: 'The two- or three-letter code for the shop\'s province or state.']
    "requires_extra_payments_agreement" varchar [note: 'Boolean representing whether the shop requires an extra Shopify Payments agreement.']
    "setup_required" varchar [note: 'Boolean representing whether the shop has any outstanding setup steps.']
    "shop_owner" varchar [note: 'The username of the shop owner.']
    "source" varchar [note: 'The handle of the partner account that referred the merchant to Shopify, if applicable.']
    "tax_shipping" varchar [note: 'Boolean representing whether taxes are charged for shipping. Valid values are true or false.']
    "taxes_included" varchar [note: 'Boolean representing whether applicable taxes are included in product prices. Valid values are true or null.']
    "timezone" varchar [note: 'The name of the timezone the shop is in.']
    "updated_at" varchar [note: 'The date and time (ISO 8601) when the shop was last updated.']
    "weight_unit" varchar [note: 'The default unit of weight measurement for the shop.']
    "zip" varchar [note: 'The shop\'s zip or postal code.']
}

Table "tender_transaction" {
    "_fivetran_synced" varchar [note: '{{ doc(\'_fivetran_synced\') }}']
    "amount" varchar [note: 'The amount of the tender transaction in the shop\'s currency.']
    "currency" varchar [note: 'The three-letter code (ISO 4217 format) for the currency used for the tender transaction.']
    "id" varchar [note: 'The ID of the transaction.']
    "order_id" varchar [note: 'The ID of the order that the tender transaction belongs to.']
    "payment_method" varchar [note: '''Information about the payment method used for this transaction. Valid values include: - credit_card - cash - android_pay - apple_pay - google_pay - samsung_pay - shopify_pay - amazon - klarna - paypal - unknown - other
    ''']
    "processed_at" varchar [note: 'The date and time (ISO 8601 format) when the tender transaction was processed.']
    "remote_reference" varchar [note: 'The remote (gateway) reference associated with the tender.']
    "test" varchar [note: 'Whether the tender transaction is a test transaction.']
    "user_id" varchar [note: 'The ID of the user logged into the Shopify POS device that processed the tender transaction, if applicable.']
}

Table "abandoned_checkout_discount_code" {
    "_fivetran_synced" varchar [note: '{{ doc(\'_fivetran_synced\') }}']
    "amount" varchar [note: 'The amount of the discount in presentment currency.']
    "checkout_id" varchar [note: 'ID of the checkout.']
    "code" varchar [note: 'The discount code.']
    "created_at" varchar [note: 'When the checkout discount application was created.']
    "discount_id" varchar [note: 'ID of the discount. Deprecated, use `code` instead.']
    "index" varchar [note: 'Index (from 1) representing the application of the discount to the checkout. Use the latest (highest index)']
    "type" varchar [note: 'The type of discount. Valid values - percentage, shipping, fixed_amount. (default - fixed_amount)']
    "updated_at" varchar [note: 'When the checkout\'s discount was last updated']
}

Table "order_discount_code" {
    "_fivetran_synced" varchar [note: '{{ doc(\'_fivetran_synced\') }}']
    "amount" varchar [note: 'The amount that\'s deducted from the order total.']
    "code" varchar [note: 'This property returns the discount code that was entered at checkout. Otherwise this property returns the title of the discount that was applied.']
    "order_id" varchar [note: 'Associated order ID.']
    "type" varchar [note: 'The type of discount - `fixed_amount`, `percentage`, or `shipping`.']
    "index" varchar [note: 'Pairs with `order_id` to provide unique identifier for order discount code.']
}

Table "abandoned_checkout_shipping_line" {
    "_fivetran_synced" varchar [note: '{{ doc(\'_fivetran_synced\') }}']
    "carrier_identifier" varchar [note: 'A reference to the carrier service that provided the rate. Present when the rate was computed by a third-party carrier service.']
    "checkout_id" varchar [note: 'ID of the checkout that was abandoned.']
    "code" varchar [note: 'A reference to the shipping method.']
    "delivery_category" varchar [note: 'The general classification of the delivery method.']
    "delivery_expectation_range" varchar [note: 'Expected delivery date range.']
    "delivery_expectation_range_max" varchar [note: 'Latest expected delivery date.']
    "delivery_expectation_range_min" varchar [note: 'Earliest possible expected delivery date.']
    "delivery_expectation_type" varchar [note: 'Type of expected delivery.']
    "discounted_price" varchar [note: 'The pre-tax shipping price with discounts applied in _presentment_ (customer) currency.']
    "id" varchar [note: 'Unique ID of the abandoned checkout shipping line.']
    "index" varchar [note: 'Index of the line amongst shipping lines for this checkout.']
    "original_shop_price" varchar [note: 'The pre-tax shipping price without any discounts applied in _presentment_ (customer) currency.']
    "phone" varchar [note: 'The phone number at the shipping address.']
    "price" varchar [note: 'The price of the shipping method in presentment currency.']
    "requested_fulfillment_service_id" varchar [note: 'The fulfillment service requested for the shipping method. Present if the shipping method requires processing by a third party fulfillment service.']
    "source" varchar [note: 'The channel where the checkout originated. Example value - shopify.']
    "title" varchar [note: 'The title of the shipping method. Example value - International Shipping.']
}

Table "fulfillment_event" {
    "_fivetran_deleted" varchar [note: '{{ doc(\'_fivetran_deleted\') }}']
    "_fivetran_synced" varchar [note: '{{ doc(\'_fivetran_synced\') }}']
    "address_1" varchar [note: 'The street address where the fulfillment event occurred.']
    "city" varchar [note: 'The city where the fulfillment event occurred.']
    "country" varchar [note: 'The country where the fulfillment event occurred.']
    "created_at" varchar [note: 'The date and time (ISO 8601 format) when the fulfillment event was created.']
    "estimated_delivery_at" varchar [note: '''The estimated delivery date based on the fulfillment\'s tracking number, as long as it\'s provided by one of the following carriers: USPS, FedEx, UPS, or Canada Post (Canada only).  Value is `null` if no tracking number is available or if the tracking number is from an unsupported carrier. This property is available only when carrier calculated rates are in use.
    ''']
    "fulfillment_id" varchar [note: 'An ID for the fulfillment that\'s associated with the fulfillment event.']
    "happened_at" varchar [note: 'The date and time (ISO 8601 format) when the fulfillment event occurred.']
    "id" varchar [note: 'An ID for the fulfillment event.']
    "latitude" varchar [note: 'A geographic coordinate specifying the latitude of the fulfillment event.']
    "longitude" varchar [note: 'A geographic coordinate specifying the longitude of the fulfillment event.']
    "message" varchar [note: 'An arbitrary message describing the status. Can be provided by a shipping carrier.']
    "order_id" varchar [note: 'The ID of the order that\'s associated with the fulfillment event.']
    "province" varchar [note: 'The province where the fulfillment event occurred.']
    "shop_id" varchar [note: 'An ID for the shop that\'s associated with the fulfillment event.']
    "status" varchar [note: '''The status of the fulfillment event. Valid values: - label_printed: A label for the shipment was purchased and printed. - label_purchased: A label for the shipment was purchased, but not printed. - attempted_delivery: Delivery of the shipment was attempted, but unable to be completed. - ready_for_pickup: The shipment is ready for pickup at a shipping depot. - picked_up: The fulfillment was successfully picked up. - confirmed: The carrier is aware of the shipment, but hasn\'t received it yet. - in_transit: The shipment is being transported between shipping facilities on the way to its destination. - out_for_delivery: The shipment is being delivered to its final destination. - delivered: The shipment was successfully delivered. - failure: Something went wrong when pulling tracking information for the shipment, such as the tracking number was invalid or the shipment was canceled.
    ''']
    "updated_at" varchar [note: 'The date and time (ISO 8601 format) when the fulfillment event was updated.']
    "zip" varchar [note: 'The zip code of the location where the fulfillment event occurred.']
}

Table "tax_line" {
    "_fivetran_synced" varchar [note: '{{ doc(\'_fivetran_synced\') }}']
    "index" varchar [note: 'The index of the tax line.']
    "order_line_id" varchar [note: 'The order line that this tax line is associated with.']
    "price" varchar [note: 'The amount of tax, in shop currency, after discounts and before returns.']
    "price_set" varchar [note: 'The amount of tax, in shop and presentment currencies, after discounts and before returns.']
    "rate" varchar [note: 'The proportion of the line item price that the tax represents as a decimal.']
    "title" varchar [note: 'The name of the tax.']
}