default:
  target: duckdb
  outputs:
    duckdb:
      type: duckdb
      path: target/dbt-{{ catalog_name }}.duckdb
      extensions:
        - httpfs
        - parquet
    motherduck:
      type: duckdb
      path: "md:airbyte_{{ catalog_name }}"
      extensions:
        - httpfs
        - parquet
      settings:
        motherduck_token: ${MOTHERDUCK_TOKEN}
