
-- This file was autogenerated with Morph. Please do not modify directly.

WITH
issue_labels AS (
    SELECT * FROM {{ source('github', 'issue_labels') }}
)


SELECT
    issue_labels.id AS issue_id,
    NULL AS label_id
FROM issue_labels
