
-- This file was autogenerated with Morph. Please do not modify directly.

WITH
pull_requests AS (
    SELECT * FROM {{ source('github', 'pull_requests') }}
)


SELECT
    pull_requests._airbyte_extracted_at AS issue_id,
    pull_requests._airbyte_extracted_at AS merged_at
FROM pull_requests
