
-- This file was autogenerated with Morph. Please do not modify directly.

WITH
issues AS (
    SELECT * FROM {{ source('github', 'issues') }}
)


SELECT
    issues.id AS id,
    issues.body AS body,
    issues.locked AS locked,
    NULL AS closed_at,
    issues.created_at AS created_at,
    issues.milestone.id AS milestone_id,
    issues.number AS number,
    issues.pull_request AS pull_request,
    NULL AS repository_id,
    issues.state AS state,
    issues.title AS title,
    issues.updated_at AS updated_at,
    issues.user.id AS user_id
FROM issues
