
-- This file was autogenerated with Morph. Please do not modify directly.

WITH
issues AS (
    SELECT * FROM {{ source('github', 'issues') }}
)


SELECT
    issues.id AS issue_id,
    issues.updated_at AS updated_at,
    NULL AS closed
FROM issues
