
-- This file was autogenerated with Morph. Please do not modify directly.

WITH
comments AS (
    SELECT * FROM {{ source('github', 'comments') }}
)


SELECT
    comments.id AS id,
    NULL AS issue_id,
    comments.user.id AS user_id,
    comments.created_at AS created_at
FROM comments
