
-- This file was autogenerated with Morph. Please do not modify directly.

WITH
issue_labels AS (
    SELECT * FROM {{ source('github', 'issue_labels') }}
)


SELECT
    issue_labels.id AS id,
    issue_labels._airbyte_extracted_at AS _fivetran_synced,
    issue_labels.color AS color,
    issue_labels.description AS description,
    issue_labels.default AS is_default,
    issue_labels.name AS name,
    issue_labels.url AS url
FROM issue_labels
