
-- This file was autogenerated with Morph. Please do not modify directly.

WITH
reviews AS (
    SELECT * FROM {{ source('github', 'reviews') }}
)


SELECT
    reviews.id AS id,
    reviews.pull_request_url AS pull_request_id,
    reviews.submitted_at AS submitted_at,
    reviews.state AS state,
    reviews.user.id AS user_id
FROM reviews
