
-- This file was autogenerated with Morph. Please do not modify directly.

WITH
review_comments AS (
    SELECT * FROM {{ source('github', 'review_comments') }}
)


SELECT
    review_comments.id AS id,
    review_comments.pull_request_review_id AS pull_request_id,
    NULL AS submitted_at,
    NULL AS state,
    review_comments.user.id AS user_id
FROM review_comments
