
-- This file was autogenerated with Morph. Please do not modify directly.

WITH
repositories AS (
    SELECT * FROM {{ source('github', 'repositories') }}
)


SELECT
    repositories.id AS id,
    repositories.created_at AS created_at,
    repositories.full_name AS full_name,
    repositories.private AS private
FROM repositories
