
-- This file was autogenerated with Morph. Please do not modify directly.

WITH
MISSING AS (
    SELECT * FROM {{ source('github', 'MISSING') }}
)


SELECT
    NULL AS repository_id,
    NULL AS team_id
FROM MISSING
