
-- This file was autogenerated with Morph. Please do not modify directly.

WITH
teams AS (
    SELECT * FROM {{ source('github', 'teams') }}
)


SELECT
    teams._airbyte_extracted_at AS repository_id,
    teams._airbyte_extracted_at AS team_id
FROM teams
