
-- This file was autogenerated with Morph. Please do not modify directly.

WITH
teams AS (
    SELECT * FROM {{ source('github', 'teams') }}
)


SELECT
    teams.id AS id,
    teams.description AS description,
    teams.name AS name,
    teams.parent AS parent_id,
    teams.privacy AS privacy,
    teams.slug AS slug
FROM teams
