
-- This file was autogenerated with Morph. Please do not modify directly.

WITH
users AS (
    SELECT * FROM {{ source('github', 'users') }}
)


SELECT
    users.id AS id,
    users.login AS login,
    NULL AS name,
    NULL AS company
FROM users
