
-- This file was autogenerated with Airbyte Morph. Please do not modify directly.

WITH
campaigns AS (
    SELECT * FROM {{ source('iterable', 'campaigns') }}
)


SELECT
    campaigns.id AS id,
    campaigns.updatedAt AS updated_at,
    campaigns.name AS name,
    campaigns.campaignState AS campaign_state,
    campaigns.type AS type,
    campaigns.sendSize AS send_size,
    campaigns.startAt AS start_at,
    campaigns.endedAt AS ended_at,
    campaigns.createdAt AS created_at,
    campaigns.recurringCampaignId AS recurring_campaign_id,
    campaigns.createdByUserId AS created_by_user_id,
    campaigns.templateId AS template_id,
    campaigns.updatedByUserId AS updated_by_user_id,
    campaigns.messageMedium AS message_medium
FROM campaigns
