
-- This file was autogenerated with Airbyte Morph. Please do not modify directly.

WITH
channels AS (
    SELECT * FROM {{ source('iterable', 'channels') }}
)


SELECT
    channels.id AS id,
    channels.name AS name,
    channels.channelType AS channel_type,
    channels.messageMedium AS message_medium
FROM channels
