
-- This file was autogenerated with Airbyte Morph. Please do not modify directly.

WITH
lists AS (
    SELECT * FROM {{ source('iterable', 'lists') }}
)


SELECT
    lists.id AS id,
    lists.name AS name,
    lists.listType AS list_type,
    lists.createdAt AS created_at,
    NULL AS description
FROM lists
