project_id: facebook_marketing.fivetran-interop
source_name: facebook_marketing

# Target schema file snapshotted from: https://github.com/fivetran/dbt_facebook_ads_source/blob/main/models/src_facebook_ads.yml
target_dbt_schema: https://raw.githubusercontent.com/fivetran/dbt_facebook_ads_source/refs/heads/main/models/src_facebook_ads.yml
source_streams:
  # TODO: list streams to include in the source here
  - ad_account
  - ad_sets
  - ads
  - ad_creatives
  # Ad Insights Streams are SLOOOOOOOW
  # - ads_insights
  # - ads_insights_age_and_gender
  # - ads_insights_country
  # - ads_insights_region
  # - ads_insights_dma
  # - ads_insights_platform_and_device
  # - ads_insights_action_type
  # - ads_insights_action_carousel_card
  # - ads_insights_action_conversion_device
  # - ads_insights_action_product_id
  # - ads_insights_action_reaction
  # - ads_insights_action_video_sound
  # - ads_insights_action_video_type
  # - ads_insights_delivery_device
  # - ads_insights_delivery_platform
  # - ads_insights_delivery_platform_and_device_platform
  # - ads_insights_demographics_age
  # - ads_insights_demographics_country
  # - ads_insights_demographics_dma_region
  # - ads_insights_demographics_gender
  - campaigns
  - custom_conversions
  - custom_audiences
  - images
  - videos
  - activities
  # - custom_insight_stream

target_tables:
  - campaign_history
  - ad_history
  - account_history
