project_id: facebook_marketing.fivetran-interop
source_name: facebook_marketing

# Target schema file snapshotted from: https://github.com/fivetran/dbt_facebook_ads_source/blob/main/models/src_facebook_ads.yml
target_dbt_schema: https://raw.githubusercontent.com/fivetran/dbt_facebook_ads_source/refs/heads/main/models/src_facebook_ads.yml
source_streams:
  - name: ad_account
    airbyte_stream: ad_account
    target_tables:
      - account_history
  - name: ads
    airbyte_stream: ads
    target_tables:
      - ad_history
  - name: campaigns
    airbyte_stream: campaigns
    target_tables:
      - campaign_history
  - name: ad_creatives
    airbyte_stream: ad_creatives
    target_tables:
      - ad_history
target_tables:
  - campaign_history
  - ad_history
  - account_history
