domain: facebook_marketing.fivetran-interop
transforms:
  - name: basic_ad_action_values
    from:
      - ads_insights_action_type: facebook_marketing.ads_insights_action_type
    fields:
      _7_d_click:
        expression: MISSING
        description:
          Conversion metric value using an attribution window of "7 days
          after clicking the ad". Not included in downstream models by default, but
          can be added using the `facebook_ads__basic_ad_actions_passthrough_metrics`
          var.
      _fivetran_id:
        expression: MISSING
        description: Defunct field.
      _fivetran_synced:
        expression: _airbyte_extracted_at
        description: "{{ doc('_fivetran_synced') }}"
      action_type:
        expression: ads_insights_action_type.action_type
        description:
          "The kind of actions taken on your ad, Page, app or event after
          your ad was served to someone, even if they didn't click on it. Action types
          include Page likes, app installs, conversions, event responses and more.
          Actions prepended by app_custom_event come from mobile app events and actions
          prepended by offsite_conversion come from the Facebook Pixel.\n"
      ad_id:
        expression: ads_insights_action_type.ad_id
        description: The ID of the ad the report relates to.
      date:
        expression: MISSING
        description: The date of the reported performance.
      index:
        expression: MISSING
        description:
          Index reflecting the `action_type` tracked for this ad on this
          day. Column of not much consequence.
      value:
        expression: ads_insights_action_type.value
        description:
          Monetary value associated with the convesion action using the
          default attribution window.
annotations:
  approved: false
  missing_fields:
    - _7_d_click
    - _fivetran_id
    - date
    - index
  evaluation:
    source_stream_name: ads_insights_action_type
    target_table_name: basic_ad_action_values
    name_match_score: 0.5
    score: 0.4375
    explanation:
      The table mapping evaluation reflects an overall moderate confidence
      score due to several fields having 'MISSING' expressions, which were assigned
      a 0.0 score. '_fivetran_synced' is correctly mapped to '_airbyte_extracted_at',
      giving it a high confidence score. A moderate name match score was assigned
      due to imperfect matches. Fields with potential name mismatches or missing expressions
      were kept below a confidence of 0.7.
    field_mapping_evals:
      - name: _7_d_click
        expression: MISSING
        score: 0.0
        explanation: Expression is 'MISSING' leading to a low confidence score.
      - name: _fivetran_id
        expression: MISSING
        score: 0.0
        explanation: Expression is 'MISSING', indicating no confidence in mapping.
      - name: _fivetran_synced
        expression: _airbyte_extracted_at
        score: 1.0
        explanation:
          Correctly mapped to '_airbyte_extracted_at', following given
          instructions.
      - name: action_type
        expression: ads_insights_action_type.action_type
        score: 0.6
        explanation:
          Expression matches description reasonably well, though there
          might be slight uncertainties.
      - name: ad_id
        expression: ads_insights_action_type.ad_id
        score: 0.6
        explanation:
          Expression matches well with description, slight name mismatch
          might exist.
      - name: date
        expression: MISSING
        score: 0.0
        explanation: Expression is 'MISSING' leading to a low confidence score.
      - name: index
        expression: MISSING
        score: 0.0
        explanation: Expression is 'MISSING', indicating no confidence in mapping.
      - name: value
        expression: ads_insights_action_type.value
        score: 0.6
        explanation:
          Expression likely aligns with description, with some uncertainties
          involved.
