domain: facebook_marketing.fivetran-interop
transforms:
- display_name: Each record represents the daily conversion values associated with
    an ad in Facebook. This is the prebuilt `basic_ad` report broken down by `action_type`
    and `action_value`.
  id: basic_ad_action_values
  from:
  - UNKNOWN: UNKNOWN
  fields:
    _7_d_click:
      expression: MISSING
      description: Conversion metric value using an attribution window of "7 days
        after clicking the ad". Not included in downstream models by default, but
        can be added using the `facebook_ads__basic_ad_actions_passthrough_metrics`
        var.
    _fivetran_id:
      expression: MISSING
      description: Defunct field.
    _fivetran_synced:
      expression: MISSING
      description: '{{ doc(''_fivetran_synced'') }}'
    action_type:
      expression: MISSING
      description: 'The kind of actions taken on your ad, Page, app or event after
        your ad was served to someone, even if they didn''t click on it. Action types
        include Page likes, app installs, conversions, event responses and more. Actions
        prepended by app_custom_event come from mobile app events and actions prepended
        by offsite_conversion come from the Facebook Pixel.

        '
    ad_id:
      expression: MISSING
      description: The ID of the ad the report relates to.
    date:
      expression: MISSING
      description: The date of the reported performance.
    index:
      expression: MISSING
      description: Index reflecting the `action_type` tracked for this ad on this
        day. Column of not much consequence.
    value:
      expression: MISSING
      description: Monetary value associated with the convesion action using the default
        attribution window.
