project_id: greenhouse.airbyte-interop
source_name: greenhouse
# Target schema file snapshotted from: https://github.com/fivetran/dbt_greenhouse_source/blob/main/models/src_greenhouse.yml
target_dbt_schema_url: https://raw.githubusercontent.com/fivetran/dbt_greenhouse_source/refs/heads/main/models/src_greenhouse.yml
# SQL dialect configuration
sql_dialect: duckdb
subcolumn_traversal: dot_notation
