
name: "airbyte_tiktok_marketing"
version: "1.0.0"
config-version: 2

profile: "default"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  airbyte_tiktok_marketing:
    +materialized: view

    # Approved models
    
    adgroup_report_hourly:
      +materialized: table
    
    campaign_history:
      +materialized: table
    
    advertiser:
      +materialized: table
    
    campaign_report_hourly:
      +materialized: table
    
    ad_history:
      +materialized: table
    
    ad_report_hourly:
      +materialized: table
    

    # Workshop models (not yet approved)
    workshop:
      +enabled: false  # Workshop models disabled by default

vars:
  airbyte_tiktok_marketing_database: "tiktok_marketing"
  airbyte_tiktok_marketing_schema: "tiktok_marketing_raw"
