
-- This file was autogenerated with Morph. Please do not modify directly.

WITH
companies_property_history AS (
    SELECT * FROM {{ source('hubspot', 'companies_property_history') }}
)


SELECT
    companies_property_history._airbyte_extracted_at AS _fivetran_synced,
    companies_property_history.companyId AS company_id,
    companies_property_history.property AS name,
    companies_property_history.sourceType AS source,
    companies_property_history.sourceId AS source_id,
    companies_property_history.timestamp AS timestamp,
    companies_property_history.value AS value
FROM companies_property_history
