
-- This file was autogenerated with Morph. Please do not modify directly.

WITH
deals AS (
    SELECT * FROM {{ source('hubspot', 'deals') }}
)


SELECT
    deals._airbyte_extracted_at AS _fivetran_synced,
    NULL AS company_id,
    deals.properties.hs_object_id AS deal_id,
    deals.properties.dealtype AS type_id,
    NULL AS category
FROM deals
