
-- This file was autogenerated with Morph. Please do not modify directly.

WITH
email_subscriptions AS (
    SELECT * FROM {{ source('hubspot', 'email_subscriptions') }}
)


SELECT
    email_subscriptions._airbyte_extracted_at AS _fivetran_synced,
    email_subscriptions.active AS active,
    email_subscriptions.description AS description,
    email_subscriptions.id AS id,
    email_subscriptions.name AS name,
    email_subscriptions.portalId AS portal_id
FROM email_subscriptions
