
-- This file was autogenerated with Morph. Please do not modify directly.

WITH
email_events AS (
    SELECT * FROM {{ source('hubspot', 'email_events') }}
)


SELECT
    email_events._airbyte_extracted_at AS _fivetran_synced,
    email_events.id AS id,
    email_events.ipAddress AS ip_address,
    email_events.userAgent AS user_agent
FROM email_events
