
-- This file was autogenerated with Morph. Please do not modify directly.

WITH
email_events AS (
    SELECT * FROM {{ source('hubspot', 'email_events') }}
)


SELECT
    email_events._airbyte_extracted_at AS _fivetran_synced,
    email_events.bcc AS bcc,
    email_events.cc AS cc,
    email_events.dropMessage AS drop_message,
    email_events.dropReason AS drop_reason,
    email_events.from AS from,
    email_events.id AS id,
    email_events.replyTo AS reply_to,
    email_events.subject AS subject
FROM email_events
