
-- This file was autogenerated with Morph. Please do not modify directly.

WITH
email_events AS (
    SELECT * FROM {{ source('hubspot', 'email_events') }}
)


SELECT
    email_events._airbyte_extracted_at AS _fivetran_synced,
    email_events.bounced AS bounced,
    email_events.id AS id,
    email_events.portalSubscriptionStatus AS portal_subscription_status,
    email_events.requestedBy AS requested_by,
    email_events.source AS source,
    email_events.subscriptions AS subscriptions
FROM email_events
