
-- This file was autogenerated with Morph. Please do not modify directly.

WITH
email_events AS (
    SELECT * FROM {{ source('hubspot', 'email_events') }}
)


SELECT
    email_events._airbyte_extracted_at AS _fivetran_synced,
    email_events.attempt AS attempt,
    email_events.id AS id,
    email_events.response AS response
FROM email_events
