
-- This file was autogenerated with Morph. Please do not modify directly.

WITH
engagements_emails AS (
    SELECT * FROM {{ source('hubspot', 'engagements_emails') }}
)


SELECT
    engagements_emails._airbyte_extracted_at AS _fivetran_synced,
    engagements_emails.properties.hs_email_from_email AS email,
    engagements_emails.properties.hs_engagement_source_id AS engagement_id,
    engagements_emails.properties.hs_email_from_firstname AS first_name,
    engagements_emails.properties.hs_email_from_lastname AS last_name
FROM engagements_emails
