
-- This file was autogenerated with Morph. Please do not modify directly.

WITH
engagements_calls AS (
    SELECT * FROM {{ source('hubspot', 'engagements_calls') }}
)


SELECT
    engagements_calls._airbyte_extracted_at AS _fivetran_synced,
    engagements_calls.id AS engagement_id,
    NULL AS _fivetran_deleted,
    engagements_calls.properties.hs_createdate AS property_hs_createdate,
    engagements_calls.properties.hs_timestamp AS timestamp,
    engagements_calls.properties.hs_user_ids_of_all_owners AS property_hubspot_owner_id,
    engagements_calls.properties.hs_team_id AS property_hubspot_team_id
FROM engagements_calls
