
-- This file was autogenerated with Morph. Please do not modify directly.

WITH
engagements AS (
    SELECT * FROM {{ source('hubspot', 'engagements') }}
)


SELECT
    engagements._airbyte_extracted_at AS _fivetran_synced,
    NULL AS _fivetran_deleted,
    engagements.id AS engagement_id,
    engagements.createdAt AS property_hs_createdate,
    engagements.timestamp AS property_hs_timestamp,
    engagements.type AS type
FROM engagements
