
-- This file was autogenerated with Morph. Please do not modify directly.

WITH
owners AS (
    SELECT * FROM {{ source('hubspot', 'owners') }}
)


SELECT
    owners._airbyte_extracted_at AS _fivetran_synced,
    owners.userId AS active_user_id,
    owners.createdAt AS created_at,
    owners.email AS email,
    owners.firstName AS first_name,
    owners.lastName AS last_name,
    owners.id AS owner_id,
    NULL AS portal_id,
    NULL AS type,
    owners.updatedAt AS updated_at
FROM owners
