
-- This file was autogenerated with Morph. Please do not modify directly.

WITH
deals AS (
    SELECT * FROM {{ source('hubspot', 'deals') }}
)


SELECT
    deals._airbyte_extracted_at AS _fivetran_synced,
    NULL AS ticket_id,
    deals.id AS deal_id,
    NULL AS category
FROM deals
