
-- This file was autogenerated with Morph. Please do not modify directly.

WITH
tickets AS (
    SELECT * FROM {{ source('hubspot', 'tickets') }}
)


SELECT
    tickets._airbyte_extracted_at AS _fivetran_synced,
    tickets.properties.hs_ticket_id AS ticket_id,
    tickets.properties.hs_primary_company_id AS company_id,
    tickets.properties.hs_ticket_category AS category
FROM tickets
