
-- This file was autogenerated with Morph. Please do not modify directly.

WITH
engagements AS (
    SELECT * FROM {{ source('hubspot', 'engagements') }}
)


SELECT
    engagements._airbyte_extracted_at AS _fivetran_synced,
    engagements.associations_ticketIds AS ticket_id,
    engagements.id AS engagement_id,
    NULL AS category
FROM engagements
