
-- This file was autogenerated with Morph. Please do not modify directly.

WITH
contacts AS (
    SELECT * FROM {{ source('hubspot', 'contacts') }}
)


SELECT
    contacts._airbyte_extracted_at AS _fivetran_synced,
    NULL AS ticket_id,
    contacts.id AS contact_id,
    NULL AS category
FROM contacts
