domain: hubspot.fivetran-compat
transforms:
  - display_name: Fivetran Raw 'Product' Model
    id: product
    from:
      - products: airbyte_raw_hubspot.products
    fields:
      # Fields in target schema order
      _fivetran_synced:
        expression: MISSING
        description: "Timestamp of when this record was last synced by Fivetran."
      id:
        expression: products.id
        description: "The ID of the product."
      portal_id:
        expression: MISSING
        description: "The HubSpot account ID."
      is_deleted:
        expression: products.archived
        description: "Whether the record was deleted."
      name:
        expression: products.properties_name
        description: "The name of the product."
      description:
        expression: products.properties_description
        description: "A description of the product."
      created_at:
        expression: products.createdAt
        description: "The date the product was created."
      updated_at:
        expression: products.updatedAt
        description: "The date the product was last updated."
      price:
        expression: products.properties_price
        description: "The price of the product."
      hs_sku:
        expression: products.properties_hs_sku
        description: "The SKU of the product."
      hs_recurring_billing_period:
        expression: products.properties_hs_recurring_billing_period
        description: "The recurring billing period of the product."
      hs_product_type:
        expression: products.properties_hs_product_type
        description: "The type of the product."

    annotations:
      unused_source_fields:
        products:
          # alpha-sorted list of unused properties from the products schema:
          - archived
          - properties
