domain: hubspot.fivetran-compat
transforms:
  - display_name: Fivetran Raw 'Workflow' Model
    id: workflow
    from:
      - workflows: airbyte_raw_hubspot.workflows
    fields:
      # Fields in target schema order
      _fivetran_synced:
        expression: MISSING
        description: "Timestamp of when this record was last synced by Fivetran."
      id:
        expression: workflows.id
        description: "The ID of the workflow."
      portal_id:
        expression: MISSING
        description: "The HubSpot account ID."
      is_deleted:
        expression: false
        description: "Whether the record was deleted."
      name:
        expression: workflows.name
        description: "The name of the workflow."
      type:
        expression: workflows.type
        description: "The type of the workflow."
      enabled:
        expression: workflows.enabled
        description: "Whether the workflow is enabled."
      inserted_at:
        expression: workflows.insertedAt
        description: "The date the workflow was created."
      updated_at:
        expression: workflows.updatedAt
        description: "The date the workflow was last updated."
      actions:
        expression: workflows.actions
        description: "The actions performed by the workflow."
      allow_contact_to_trigger_multiple_times:
        expression: workflows.allowContactToTriggerMultipleTimes
        description: "Whether a contact can trigger the workflow multiple times."
      listening_triggers:
        expression: workflows.listeningTriggers
        description: "The triggers that the workflow is listening for."
      suppressed:
        expression: workflows.suppressed
        description: "Whether the workflow is suppressed."

    annotations:
      unused_source_fields:
        workflows:
          # alpha-sorted list of unused properties from the workflows schema:
          - createdAt
          - personaTagIds
