name: On-Demand Generate

on:
  workflow_dispatch:
    inputs:
      # Note: This will not work as a slash command
      # until we add a step to parse `source_name`
      # from `comment-text`.
      source_name:
        description: "Source Name (e.g., hubspot, facebook_marketing)"
        type: string
        required: true
      pr:
        description: "PR Number"
        type: number
        required: false
      comment-id:
        description: "Comment ID (Optional)"
        type: number
        required: false

jobs:
  run-poe-command:
    runs-on: ubuntu-latest

    steps:
      - name: Run Poe Slash Command Processor
        uses: aaronsteers/poe-command-processor@v1.0.0
        with:
          command: "morph-generate ${{ github.event.inputs.source_name }}"
          pr: ${{ github.event.inputs.pr }}
          comment-id: ${{ github.event.inputs.comment-id }}
          github-token: ${{ secrets.GH_PAT_MAINTENANCE_OCTAVIA }}
