name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Setup uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.11"
      - name: Create virtual environment
        run: uv venv
      - name: Install poethepoet
        run: uv pip install poethepoet
      - name: Install dependencies
        run: poe install
      - name: Lint with ruff
        run: poe lint
