name: On-Demand Lock

on:
  workflow_dispatch:
    inputs:
      pr:
        description: "PR Number"
        type: string
        required: true
      comment-id:
        description: "Comment ID (Optional)"
        type: string
        required: false
      comment-text:
        description: "Full comment text (ignored)"
        type: string
        required: false

jobs:
  run-poe-command:
    runs-on: ubuntu-latest

    steps:
      - name: Run Poe Slash Command Processor
        uses: aaronsteers/poe-command-processor@main
        with:
          command: "lock"
          pr: ${{ github.event.inputs.pr }}
          comment-id: ${{ github.event.inputs.comment-id }}
          github-token: ${{ secrets.GH_PAT_MAINTENANCE_OCTAVIA }}
