name: On-Demand Poe Task

on:
  workflow_dispatch:
    inputs:
      pr:
        description: "PR Number"
        type: string
        required: true
      comment-id:
        description: "Comment ID (Optional)"
        type: string
        required: false
      comment-text:
        description: "Full comment text (Optional)"
        type: string
        required: false

permissions:
  contents: write
  pull-requests: write

jobs:
  run-poe-command:
    runs-on: ubuntu-latest

    steps:
      - name: Get Poe Command
        id: get-command
        run: |
            poe-command=$(echo "${{ github.event.inputs.comment-text }}" | sed 's|^/||' | head -n 1) >> $GITHUB_OUTPUT
            echo "command=${command}"

      - name: Run Poe Slash Command Processor
        uses: aaronsteers/poe-command-processor@main
        with:
          command: ${{ steps.get-command.outputs.poe-command }}
          pr: ${{ github.event.inputs.pr }}
          comment-id: ${{ github.event.inputs.comment-id }}
          github-token: ${{ secrets.GH_PAT_MAINTENANCE_OCTAVIA }}
