name: Slash Commands

on:
  issue_comment:
    types: [created]

jobs:
  slash-command:
    runs-on: ubuntu-latest
    if: startsWith(github.event.comment.body, '/')
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.12"

      - name: Create virtual environment
        run: uv venv

      - name: Install poethepoet
        run: uv pip install poethepoet

      - name: Install dependencies
        run: poe install

      - name: Run /fix command
        if: startsWith(github.event.comment.body, '/fix')
        run: |
          poe fix
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git diff --staged --quiet || git commit -m "Apply automatic fixes from /fix command"
          git push

      - name: Run /lock command
        if: startsWith(github.event.comment.body, '/lock')
        run: |
          poe lock
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add requirements.lock
          git diff --staged --quiet || git commit -m "Update dependency lock file from /lock command"
          git push

      - name: Run /test command
        if: startsWith(github.event.comment.body, '/test')
        run: |
          # This would run tests that require credentials
          # For community PRs, this is useful since the workflow has access to secrets
          # that are not available to workflows triggered by PRs from forks
          poe pytest
